---
- name: Pause until Connections is up - "https://{{ __cnx_url }}/homepage/login"
  uri:
    url: "https://{{ __cnx_url }}/homepage/login"
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 20
  delay: 30
