---
# Mandatory changes!

cnx_component_pack_ingress:                      "connections.internal"
cnx_application_ingress:                         "connections.internal"

# Usernames and password for eventual customization. Shown here are default usernames and password. Change it to customize it

was_username:                                    wasadmin
was_password:                                    password

ldap_userid:                                     "fakeuser"
ldap_nr_of_users:                                10
ldap_user_password:                              "password"
ldap_user_admin_password:                        "password"

ihs_username:                                    ihsadmin
ihs_password:                                    password

connections_admin:                               fakeuser1

db_password:                                     password
db_concord_password:                             password

docs_username:                                   docsuser
docs_password:                                   password
sudo_group:                                      wheel

# Non-mandatory changes

# Type of HCL Connections deployment: small (default), medium and large.
#cnx_deploy_type:                                small
ldap_user_mail_domain:                           "connections.internal"

db2_download_location:                           http://{{ groups['installer'][0] }}:8001/
tdi_download_location:                           http://{{ groups['installer'][0] }}:8001/
connections_wizards_download_location:           http://{{ groups['installer'][0] }}:8001/
iim_repository_url:                              http://{{ groups['installer'][0] }}:8001/
was_repository_url:                              http://{{ groups['installer'][0] }}:8001/
was_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/
ihs_repository_url:                              http://{{ groups['installer'][0] }}:8001/
ihs_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/
cnx_docs_download_location:                      http://{{ groups['installer'][0] }}:8001/
cnx_repository_url:                              http://{{ groups['installer'][0] }}:8001/
component_pack_download_location:                http://{{ groups['installer'][0] }}:8001/

upgrade_tdi_jre:                                 true
tdi_sol_location:                                http://{{ groups['installer'][0] }}:8001/tdisol_70_java8.tar

cnx_updates_enabled:                             True

dmgr_hostname:                                   "{{ hostvars[groups['dmgr'][0]]['inventory_hostname'] }}"

smtp_hostname:                                   localhost

connections_admin_password:                      "{{ ldap_user_admin_password }}"

db_username:                                     LCUSER
db_concord_username:                             docsuser
db_hostname:                                     "{{ hostvars[groups['db_servers'][0]]['inventory_hostname'] }}"
db_port:                                         50000
#db_jdbc_file:                                    /opt/IBM/db2/V11.1/java
db_type:                                         DB2
setup_db2_jdbc:                                  True

cnx_force_repopulation:                          false

cnx_enable_moderation:                           true
cnx_enable_invite:                               true
cnx_enable_full_icec:                            true

enable_prometheus_jmx_exporter:                  True

# uncomment these lines, set to the latest cFix to include it as part of the initial install
# ifix_apar:                                       CFix.70.2110
# cnx_ifix_installer:                              "updateInstaller_2104.zip"
# ifix_file:                                       CFix.70.2110-IC7.0.0.0-Common-Fix.jar

setup_docker_registry:                           true
component_pack_package_name:                     component_pack_latest.zip

docker_registry_url:                             "{{ hostvars[groups['docker_registry'][0]]['inventory_hostname'] }}:5000"
load_balancer_dns:                               "{{ hostvars[groups['k8s_load_balancers'][0]]['inventory_hostname'] }}"
ic_internal:                                     "{{ hostvars[groups['ihs_servers'][0]]['inventory_hostname'] }}"
frontend_fqdn:                                   "{{ cnx_application_ingress }}"
frontend_domain:                                 "{{ cnx_application_ingress.split('.')[1:] | join('.') }}"
db_server:                                       "{{ db_hostname }}"
db_server_user:                                  "{{ db_username }}"
db_server_password:                              "{{ db_password }}"

setup_connections_docs:                          true

nfs_export_netmask:                              255.0.0.0
skip_nfs_mount_for_connections:                  true

docs_shared_storage_type:                        nfs
docs_data_remote_path:                           /nfs/docs_data
docs_data_local_path:                            /mnt/docs_data

viewer_shared_storage_type:                      nfs
viewer_data_remote_path:                         /nfs/viewer_data
viewer_data_local_path:                          /mnt/viewer_data

cnx_shared_storage_type:                         nfs
cnx_data_remote_path:                            /nfs/data/shared
cnx_data_local_path:                             /mnt/cnx_data

cnx_data_path_on_cnx_server:                     /opt/IBM/SharedArea

docs_url:                                        "{{ cnx_application_ingress }}"

force_destroy_kubernetes:                        True
force_destroy_db2:                               True
force_destroy_ihs:                               True
force_destroy_websphere:                         True
