---
- name:                     "Skip extended user setup when 'connections_extended_user' is not set"
  debug:
    msg:                    "'connections_extended_user' is empty or undefined; skipping extended user setup."
    verbosity:              1
  when:                     connections_extended_user | default('') | trim | length == 0

- name:                     "Render {{ __cnx_extend_user_destination }}"
  template:
    src:                    "{{ __cnx_extend_user_template }}"
    dest:                   "{{ __cnx_extend_user_destination }}"
  delegate_to:              "{{ dmgr_hostname }}"
  when:                     connections_extended_user | default('') | trim | length > 0

- name:                     "Register extended user {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __cnx_extend_user_destination }}"
  command:                  "{{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __cnx_extend_user_destination }}"
  args:
    chdir:                  "{{ __dmgr_bin_dir }}"
  delegate_to:              "{{ dmgr_hostname }}"
  register:                 result
  when:                     connections_extended_user | default('') | trim | length > 0
  retries: 20
  delay: 10
  until: result is succeeded
