---
- name:                      Check the vars
  include_tasks:             check_vars.yml

- name:                      Prepare Component Pack
  include_tasks:             setup_installation.yml
  when:                      __setup_installation |bool

- name:                      Configure credentials
  include_tasks:             configure_credentials.yml
  when:                      __setup_credentials |bool

- name:                      Configure PSP
  include_tasks:             configure_psp.yml

- name:                      Setup connections-volumes
  include_tasks:             setup_connections_volumes.yml
  when:                      __setup_connections_volumes |bool

- name:                      Setup Bootstrap
  include_tasks:             setup_bootstrap.yml
  when:                      __setup_bootstrap |bool

- name:                      Setup connections-env
  include_tasks:             setup_connenv.yml
  when:                      __setup_connections_env |bool

- name:                      Setup infrastructure
  include_tasks:             setup_infrastructure.yml
  when:                      __setup_infrastructure |bool

- name:                      Setup customizer
  include_tasks:             setup_customizer.yml
  when:                      __setup_customizer |bool

- name:                      Setup elasticsearch 7
  include_tasks:             setup_elasticsearch7.yml
  when:                      __setup_elasticsearch7 |bool

- name:                      Setup opensearch
  include_tasks:             setup_opensearch.yml
  when:                      __setup_opensearch |bool

- name:                      Check if opensearch is deployed and pod is in running state
  shell:                     "kubectl wait -n {{ __default_namespace }} --for=jsonpath='{.status.phase}'=Running  pods --selector app.kubernetes.io/name='opensearch' --timeout=1s"
  register:                  opensearch_pod_running
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Set __setup_opensearch variable if opensearch is deployed and pod is in running state
  set_fact:
    __setup_opensearch:      true
  when:                      opensearch_pod_running.stdout != ""

- name:                      Setup Community Ingress Controller
  include_tasks:             setup_community_ingress.yml
  when:                      __setup_community_ingress |bool

- name:                      Setup Teams
  include_tasks:             setup_teams.yml
  when:                      __setup_teams |bool

- name:                      Setup Tailored Experience
  include_tasks:             setup_tailored_exp.yml
  when:                      __setup_tailored_exp |bool

- name:                      Check if Tailored Experience is deployed and pod is in running state
  shell:                     "kubectl wait -n {{ __default_namespace }} --for=jsonpath='{.status.phase}'=Running  pods --selector app='te-creation-wizard' --timeout=1s"
  register:                  tailored_exp_pod_running
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Set __setup_tailored_exp variable if Tailored Experience is deployed and pod is in running state
  set_fact:
    __setup_tailored_exp:    true
  when:                      tailored_exp_pod_running.stdout != ""

- name:                      Setup ELK
  include_tasks:             setup_elasticstack7.yml
  when:                      __setup_elasticstack7 |bool

- name:                      Setup ELK-7 stack
  include_tasks:             setup_elasticstack7.yml
  when:                      __setup_elasticstack7 |bool

- name:                      Setup OpenSearch stack
  include_tasks:             setup_opensearchstack.yml
  when:                      __setup_opensearchstack |bool

- name:                      Setup orientme
  include_tasks:             setup_orientme.yml
  when:                      __setup_orientme |bool

- name:                      Run profiles migration for OrientMe
  include_tasks:             orientme_profile_migration.yml
  when:
   - __setup_orientme |bool
   - not __skip_connections_integration

- name:                      Setup Activities Plus
  include_tasks:             setup_kudosboards.yml
  when:
   - __setup_huddoboards |bool
   - not __skip_connections_integration

- name:                      Setup Outlook Desktop Plugin
  include_tasks:             setup_outlook_addin.yml
  when:
   - __setup_outlook_addin |bool
   - not __skip_connections_integration

- name:                      Scale to the number of nodes
  include_tasks:             scale_component_pack.yml
  when:                      __enable_pod_auto_scaling |bool

- name:                      Enable ES metrics
  include_tasks:             enable_es_metrics.yml
  when:
   - __enable_es_metrics |bool
   - __setup_elasticsearch7 |bool or __setup_elasticsearch |bool or __setup_opensearch |bool
   - not __skip_connections_integration

- name:                      Setup GK flags
  include_tasks:             setup_gk_flags.yml
  when:
   - __enable_gk_flags |bool
   - not __skip_connections_integration

- name:                      Setup MS Teams Extensions
  include_tasks:             setup_ms_teams_extensions.yml
  when:
   - __setup_ms_teams_extensions |bool
   - not __skip_connections_integration

- name:                      Verify all deplyments/statefulsets are rolled out successfully
  include_tasks:             verify_deployment_rollout_status.yml
