- name:                    Get No of workers
  set_fact:
     count_workers:        "{{ groups['k8s_workers'] | length }}"

- name:                    Scale Component Pack to the number of workers
  shell:                   kubectl scale --replicas={{ count_workers }} deployment $(kubectl get deployment -n {{ __default_namespace }} | awk {'print $1'} | grep -v NAME) -n {{ __default_namespace }}
  become_user:             "{{ __sudo_user }}"
