- name:                     "Render {{ __outlook_reg_destination }}"
  template:
    src:                    "{{ __outlook_reg_template }}"
    dest:                   "{{ __outlook_reg_destination }}"
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Register Connections Outlook Desktop Addin"
  command:
    chdir={{ __dmgr_bin_dir }}
    {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __outlook_reg_destination }}
  register:                 outlook_addin
  changed_when:             outlook_addin.rc == 0
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Show me the secret"
  debug:
    msg:                    "{{ outlook_addin.stdout_lines | last }}"

- name:                      "Render {{ __outlook_addin_destination }}"
  template:
    src:                     "{{ __outlook_addin_template }}"
    dest:                    "{{ __outlook_addin_destination }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "cat {{ __ansible_cache_charts }}/helm_repo_version_list | grep connections-outlook-desktop | cut -d ':' -f2"
  register:                  connections_outlook_desktop_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found connections-outlook-desktop chart version
  debug:
    msg:                     "{{ connections_outlook_desktop_chart_version.stdout }}"

- name:                      Record connections-outlook-desktop chart version
  local_action:
    module:                  shell
    cmd:                     echo "connections-outlook-desktop chart = {{ connections_outlook_desktop_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade connections-outlook-desktop
  command:                   "helm upgrade connections-outlook-desktop {{ __helm_repository_local_name }}/connections-outlook-desktop -i --version {{ connections_outlook_desktop_chart_version.stdout }} -f {{ __outlook_addin_destination }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"
