- name:                      Check if customizer is already provisioned
  shell:                     "helm ls --namespace {{ __default_namespace }} | grep mw-proxy | grep -i DEPLOYED"
  changed_when:              true
  register:                  customizer_completed
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Get nobody/nogroup
  set_fact:
    nobody:                  "{{ nfs_nobody | default('nobody') }}"
    nogroup:                 "{{ nfs_nogroup | default('nobody') }}"

- name:                      Copy HelloWorld js for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "{{ __customizer_helloworld_js_files }}"
    dest:                    "{{ __customizer_helloworld_js_dest }}"
    owner:                   "1000"
    group:                   "{{ nogroup }}"
    mode:                    '0700'
    directory_mode:          '0700'
  delegate_to:               "{{ groups['nfs_servers'][0] }}"


- name:                      Copy *.js stuff for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "{{ item }}"
    dest:                    "{{ __customizer_js_files_mount }}"
    owner:                   "1000"
    group:                   "{{ nogroup }}"
    mode:                    '0700'
    directory_mode:          '0700'
  with_items:
   - "files/customizer/container.css"
   - "files/customizer/containerUtils.js"
   - "files/customizer/utils.js"
  delegate_to:               "{{ groups['nfs_servers'][0] }}"
  when:
    -  __cnx_major_version is version('7', '<=')

- name:                      Copy ms-teams stuff for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "files/ms-teams/customizations/ms-teams"
    dest:                    "{{ __customizer_js_files_mount }}"
    owner:                   "1000"
    group:                   "{{ nogroup }}"
    mode:                    '0700'
    directory_mode:          '0700'
  delegate_to:               "{{ groups['nfs_servers'][0] }}"
  when:
   - __setup_teams |bool and  __cnx_major_version is version('7', '<=')

- name:                      Copy MS Teams Share js for customizer to "{{ __customizer_share_msteam_js_dest }}"
  copy:
    src:                     "{{ __customizer_share_msteams_js_files }}"
    dest:                    "{{ __customizer_share_msteam_js_dest }}"
    owner:                   "1000"
    group:                   "{{ nogroup }}"
    mode:                    '0700'
    directory_mode:          '0700'
  delegate_to:               "{{ groups['nfs_servers'][0] }}"
  when:
    -  __cnx_major_version is version('7', '>')

- name:                      "Render {{ __customizer_env }}"
  template:
    src:                     "helmvars/customizer.yml.j2"
    dest:                    "{{ __customizer_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "cat {{ __ansible_cache_charts }}/helm_repo_version_list | grep mw-proxy | cut -d ':' -f2"
  register:                  customizer_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found mw-proxy chart version
  debug:
    msg:                     "{{ customizer_chart_version.stdout }}"

- name:                      Record mw-proxy chart version
  local_action:
    module:                  shell
    cmd:                     echo "mw-proxy chart = {{ customizer_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade mw-proxy
  command:                   "helm upgrade mw-proxy {{ __helm_repository_local_name }}/mw-proxy -i --version {{ customizer_chart_version.stdout }} -f {{ __customizer_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Check if customizer is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i mw-proxy | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
