- name:                     "Render {{ __kudos_reg_destination }}"
  template:
    src:                    "{{ __kudos_reg_template }}"
    dest:                   "{{ __kudos_reg_destination }}"
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Register Kudosboards {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __kudos_reg_destination }}"
  command:
    chdir={{ __dmgr_bin_dir }}
    {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __kudos_reg_destination }}
  register:                 kudosboards_secret
  changed_when:             kudosboards_secret.rc == 0
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Show me the secret"
  debug:
    msg:                    "{{ kudosboards_secret.stdout_lines | last }}"

- name:                      "Render {{ __kudos_boards_destination }}"
  template:
    src:                     "{{ __kudos_boards_template }}"
    dest:                    "{{ __kudos_boards_destination }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "helm search repo {{ __helm_repository_local_name }} {{ __helm_repo_flag }} | grep huddo-boards-cp | grep -v activ | awk {'print $2'}"
  register:                  kudosboards_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found kudos-boards-cp chart version
  debug:
    msg:                     "{{ kudosboards_chart_version.stdout }}"

- name:                      Record kudos-boards-cp chart version
  local_action:
    module:                  shell
    cmd:                     echo "kudos-boards-cp chart = {{ kudosboards_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade kudos-boards-cp
  command:                   "helm upgrade kudos-boards-cp {{ __helm_repository_local_name }}/huddo-boards-cp -i --version {{ kudosboards_chart_version.stdout }} -f {{ __kudos_boards_destination }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"
