- name:                      "Render {{ __elasticstack7_env }}"
  template:
    src:                     "helmvars/elasticstack7.yml.j2"
    dest:                    "{{ __elasticstack7_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version harbor OCI
  shell:                     "helm show all {{ __oci_helm_repository }}/elasticstack7 --devel | grep -oP '^version:\\s*\\K[^ ]+'"
  register:                  elasticstack7_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found elasticstack7 chart version
  debug:
    msg:                     "{{ elasticstack7_chart_version.stdout }}"

- name:                      Record elasticstack7 chart version
  local_action:
    module:                  shell
    cmd:                     echo "elasticstack7 chart = {{ elasticstack7_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade elasticstack7
  command:                   "helm upgrade elasticstack7 {{ __helm_repository_local_name }}/elasticstack7 -i --version {{ elasticstack7_chart_version.stdout }} -f {{ __elasticstack7_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Wait for Kibana, Filebeat and Logstash to come up
  pause:
    seconds:                 60

- name:                      Check if logstash-7 is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i logstash | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if kibana-7 is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i kibana | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if filebeat-7 is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i filebeat | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Finding Kibana link
  debug:
    msg:                     "You can reach your Kibana instance here: https://{{ __frontend_fqdn }}/kibana7"
