- name:                      Check if customizer is already provisioned
  shell:                     "helm ls --namespace {{ __default_namespace }} | grep mw-proxy | grep -i DEPLOYED"
  changed_when:              true
  register:                  customizer_completed
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Create local mount point "{{ __customizer_js_files_mount }}"
  file:
    path:                    "{{ __customizer_js_files_mount }}"
    state:                   directory
    mode:                    '0755'
  when:
    - customizer_completed.rc != 0

- name:                      Mount "{{ __customizer_js_files_dest }}" to "{{ __customizer_js_files_mount }}" first
  mount:
    fstype:                  nfs
    opts:                    defaults
    dump:                    0
    passno:                  0
    state:                   mounted
    src:                     "{{ __customizer_js_files_dest }}"
    path:                    "{{ __customizer_js_files_mount }}"
  when:
    - customizer_completed.rc != 0

- name:                      Copy HelloWorld js for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "{{ __customizer_helloworld_js_files }}"
    dest:                    "{{ __customizer_helloworld_js_dest }}"

- name:                      Copy *.js stuff for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "{{ item }}"
    dest:                    "{{ __customizer_js_files_mount }}"
  with_items:
   - "files/customizer/container.css"
   - "files/customizer/containerUtils.js"
   - "files/customizer/utils.js"
  when:
    -  __cnx_major_version is version('7', '<=')

- name:                      Copy ms-teams stuff for customizer to "{{ __customizer_js_files_mount }}"
  copy:
    src:                     "files/ms-teams/customizations/ms-teams"
    dest:                    "{{ __customizer_js_files_mount }}"
  when:
   - __setup_teams |bool and  __cnx_major_version is version('7', '<=')

- name:                      Copy MS Teams Share js for customizer to "{{ __customizer_share_msteam_js_dest }}"
  copy:
    src:                     "{{ __customizer_share_msteams_js_files }}"
    dest:                    "{{ __customizer_share_msteam_js_dest }}"
  when:
    -  __cnx_major_version is version('7', '>')

- name:                      "Render {{ __customizer_env }}"
  template:
    src:                     "helmvars/customizer.yml.j2"
    dest:                    "{{ __customizer_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "helm search repo {{ __helm_repository_local_name }} {{ __helm_repo_flag }} | grep mw-proxy | awk {'print $2'}"
  register:                  customizer_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found mw-proxy chart version
  debug:
    msg:                     "{{ customizer_chart_version.stdout }}"

- name:                      Record mw-proxy chart version
  local_action:
    module:                  shell
    cmd:                     echo "mw-proxy chart = {{ customizer_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade mw-proxy
  command:                   "helm upgrade mw-proxy {{ __helm_repository_local_name }}/mw-proxy -i --version {{ customizer_chart_version.stdout }} -f {{ __customizer_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Check if customizer is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i mw-proxy | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
