- name:                       Delete quay credentials, to enable recreating it
  command:                    kubectl delete secret {{ __huddoboards_credentials_name }} -n {{ __default_namespace }}
  become_user:                "{{ __sudo_user }}"
  ignore_errors:              true

- name:                       Setup credentials for quay Repository
  command:                    kubectl create secret docker-registry {{ __huddoboards_credentials_name }} -n {{ __default_namespace }} --docker-server={{ __huddoboards_registry_url }} --docker-username={{ __huddoboards_registry_username }} --docker-password {{ __huddoboards_registry_password }}
  become_user:                "{{ __sudo_user }}"

- name:                     "Render {{ __kudos_reg_destination }}"
  template:
    src:                    "{{ __kudos_reg_template }}"
    dest:                   "{{ __kudos_reg_destination }}"
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Register huddoboards {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __kudos_reg_destination }}"
  command:
    chdir={{ __dmgr_bin_dir }}
    {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __kudos_reg_destination }}
  register:                 kudosboards_secret
  changed_when:             kudosboards_secret.rc == 0
  delegate_to:              "{{ dmgr_hostname }}"

- name:                     "Show me the secret"
  debug:
    msg:                    "{{ kudosboards_secret.stdout_lines | last }}"

- name:                      "Render {{ __kudos_boards_destination }}"
  template:
    src:                     "{{ __kudos_boards_template }}"
    dest:                    "{{ __kudos_boards_destination }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Upgrade kudos-boards-cp
  command:                   "helm upgrade kudos-boards-cp {{ __huddoboards_chart_location }}/{{ __huddoboards_chart_name }}  -i -f {{ __kudos_boards_destination }} --namespace {{ __default_namespace }} --recreate-pods"
  become_user:               "{{ __sudo_user }}"
