- name:                      Get chart and version harbor OCI
  shell:                     "helm show all {{ __oci_helm_repository }}/sanity --devel | grep -oP '^version:\\s*\\K[^ ]+'"
  register:                  sanity_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found sanity chart version
  debug:
    msg:                     "{{ sanity_chart_version.stdout }}"

- name:                      Record sanity chart version
  local_action:
    module:                  shell
    cmd:                     echo "sanity chart = {{ sanity_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      "Render {{ __sanity_env }}"
  template:
    src:                     "helmvars/sanity.yml.j2"
    dest:                    "{{ __sanity_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Upgrade sanity
  command:                   "helm upgrade sanity {{ __helm_repository_local_name }}/sanity -i --version {{ sanity_chart_version.stdout }} -f {{ __sanity_env }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version harbor OCI
  shell:                     "helm show all {{ __oci_helm_repository }}/sanity-watcher --devel | grep -oP '^version:\\s*\\K[^ ]+'"
  register:                  sanity_watcher_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found sanity-watcher chart version
  debug:
    msg:                     "{{ sanity_watcher_chart_version.stdout }}"

- name:                      Record sanity-watcher chart version
  local_action:
    module:                  shell
    cmd:                     echo "sanity-watcher chart = {{ sanity_watcher_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      "Render {{ __sanity_watcher_env }}"
  template:
    src:                     "helmvars/sanity-watcher.yml.j2"
    dest:                    "{{ __sanity_watcher_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Upgrade sanity-watcher
  command:                   "helm upgrade sanity-watcher {{ __helm_repository_local_name }}/sanity-watcher -i --version {{ sanity_watcher_chart_version.stdout }} -f {{ __sanity_watcher_env }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get the port where Sanity is running
  shell:                     kubectl get --namespace {{ __default_namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services sanity
  register:                  sanity_external_port
  become_user:               "{{ __sudo_user }}"

- name:                      Get the IP where Sanity is accessible
  shell:                     kubectl get nodes --namespace {{ __default_namespace }} -o jsonpath="{.items[0].status.addresses[0].address}"
  register:                  sanity_external_ip
  become_user:               "{{ __sudo_user }}"

- name:                      You can access Sanity here
  debug:
    msg:                     "http://{{ sanity_external_ip['stdout'] }}:{{ sanity_external_port['stdout'] }}"
