- name:                      "Render {{ __opensearchstack_env }}"
  template:
    src:                     "helmvars/opensearchstack.yml.j2"
    dest:                    "{{ __opensearchstack_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "helm search repo {{ __helm_repository_local_name }} {{ __helm_repo_flag }} | grep opensearchstack | awk {'print $2'}"
  register:                  opensearchstack_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found OpenSearch Stack chart version
  debug:
    msg:                     "{{ opensearchstack_chart_version.stdout }}"

- name:                      Record OpenSearch Stack chart version
  local_action:
    module:                  shell
    cmd:                     echo "opensearchstack chart = {{ opensearchstack_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade OpenSearch Stack
  command:                   "helm upgrade opensearchstack {{ __helm_repository_local_name }}/opensearchstack -i --version {{ opensearchstack_chart_version.stdout }} -f {{ __opensearchstack_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Wait for OpenSearch Dashboard, OpenSearch Filebeat and OpenSearch Logstash to come up
  pause:
    seconds:                 60

- name:                      Check if OpenSearch Logstash is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i opensearch-logstash | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if Opensearch Dashboard is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i opensearch-kibana | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if OpenSearch Filebeat is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i opensearch-filebeat | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Finding OpensSearch-Dashboard link
  debug:
    msg:                     "You can reach your opensearch-dashboard instance here: https://{{ __frontend_fqdn }}/opensearch-dashboard"
