- name:                      "Render {{ __teams_env }}"
  template:
    src:                     "helmvars/teams.yml.j2"
    dest:                    "{{ __teams_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Get chart and version
  shell:                     "cat {{ __ansible_cache_charts }}/helm_repo_version_list | grep teams | grep -vE teams- | cut -d ':' -f2"
  register:                  teams_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found teams chart version
  debug:
    msg:                     "{{ teams_chart_version.stdout }}"

- name:                      Record teams chart version
  local_action:
    module:                  shell
    cmd:                     echo "teams chart = {{ teams_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                    false
  when:                      __record_cp_versions|bool

- name:                      Upgrade teams
  command:                   "helm upgrade teams {{ __helm_repository_local_name }}/teams -i --version {{ teams_chart_version.stdout }} -f {{ __teams_env }} --namespace {{ __default_namespace }} --wait"
  become_user:               "{{ __sudo_user }}"

- name:                      Check if teams share service is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i teams-share-service | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if teams share ui is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i teams-share-ui | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if teams tab api is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i teams-tab-api | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if teams tab ui is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i teams-tab-ui | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
