- name:                      Get chart and version harbor OCI
  shell:                     "helm show all {{ __oci_helm_repository }}/k8s-psp --devel | grep -oP '^version:\\s*\\K[^ ]+'"
  register:                  k8s_psp_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                    Found PSP chart version
  debug:
    msg:                   "{{ k8s_psp_chart_version.stdout }}"

- name:                    Record PSP chart version
  local_action:
    module:                shell
    cmd:                   echo "k8s-psp chart = {{ k8s_psp_chart_version.stdout }}" >> "{{ __cp_versions_file }}"
  become:                  false
  when:                    __record_cp_versions|bool

- name:                    Upgrade PSP
  command:                 "helm upgrade k8s-psp {{ __helm_repository_local_name }}/k8s-psp -i --version {{ k8s_psp_chart_version.stdout }} --set namespace={{ __default_namespace }} --namespace {{ __default_namespace }} --wait"
  become_user:             "{{ __sudo_user }}"
