- name:                      Add Community Helm Repo
  shell:                     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Check cluster flavor Vannila/EKS/Openshift
  shell:                     kubectl cluster-info | head -1
  register:                  cluster_flavor_check
  # grep will exit with 1 when no results found.
  # This causes the task not to halt play.
  become_user:               "{{ __sudo_user }}"

- debug: var=cluster_flavor_check
  run_once: true

- name:                      Check if cnx-ingress is already deployed
  shell:                     helm ls --all-namespaces | grep cnx-ingress | grep -i DEPLOYED
  changed_when:              true
  register:                  cnx_ingress_already_provisioned
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Delete cnx-ingress if already exists
  shell:                     helm uninstall cnx-ingress --namespace {{ __default_namespace }}
  when:
   - cnx_ingress_already_provisioned.rc == 0
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Delete configmaps
  shell:                     kubectl delete configmaps ingress-controller-leader ingress-controller-leader-nginx -n {{ __default_namespace }}
  when:
   - cnx_ingress_already_provisioned.rc == 0
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name:                      Give it some space...
  pause:
    seconds:                 15

- name:                      Check if prom-operator is already deployed
  shell:                     helm ls --all-namespaces | grep prom-operator | grep -i DEPLOYED
  changed_when:              true
  register:                  prom_operator_already_provisioned
  become_user:               "{{ __sudo_user }}"
  ignore_errors:             true

- name: Render cnx_ingress_values.j2 from local host to remote host $HOME/cnx-ingress-values.yml (relative path, ./template/)
  template:
    src: cnx-ingress-values.j2
    dest: $HOME/cnx-ingress-values.yml
    mode:                    '0777'
  become_user:               "{{ __sudo_user }}"

- name:                      Install ingress-nginx - if Vanilla Kubernetes if Prom-Operator already Deployed
  shell:                     helm upgrade cnx-ingress -i ingress-nginx/ingress-nginx --namespace {{ __default_namespace }} --set {{ __communityingress_env_vanilla }} -f $HOME/cnx-ingress-values.yml --wait
  when:
   - prom_operator_already_provisioned.rc == 0
   - ("eks.amazonaws.com" not in cluster_flavor_check.stdout) and  ("api." not in cluster_flavor_check.stdout)
  become_user:               "{{ __sudo_user }}"

- name:                      Install ingress-nginx - if Vanilla Kubernetes if Prom-Operator NOT already Deployed
  shell:                     helm upgrade cnx-ingress -i ingress-nginx/ingress-nginx --namespace {{ __default_namespace }} --set controller.image.allowPrivilegeEscalation=false --set {{ __communitying_ind_env_vanilla }} --wait
  when:
   - prom_operator_already_provisioned.rc != 0
   - ("eks.amazonaws.com" not in cluster_flavor_check.stdout) and  ("api." not in cluster_flavor_check.stdout)
  become_user:               "{{ __sudo_user }}"

- name:                      Install ingress-nginx - if EKS/OpenShift  if Prom-Operator already Deployed
  shell:                     helm upgrade cnx-ingress -i ingress-nginx/ingress-nginx --namespace {{ __default_namespace }} --set {{ __communityingress_env_eks_os }} -f cnx-ingress-values.yml --wait
  when:
   - ("eks.amazonaws.com" in cluster_flavor_check.stdout) or  ("api." in cluster_flavor_check.stdout)
   - prom_operator_already_provisioned.rc == 0
  become_user:               "{{ __sudo_user }}"

- name:                      Install ingress-nginx - if EKS/OpenShift  if Prom-Operator NOT already Deployed
  shell:                     helm upgrade cnx-ingress -i ingress-nginx/ingress-nginx --namespace {{ __default_namespace }} --set controller.image.allowPrivilegeEscalation=false --set {{ __communitying_ind_env_eks_os }} --wait
  when:
   - ("eks.amazonaws.com" in cluster_flavor_check.stdout) or  ("api." in cluster_flavor_check.stdout)
   - prom_operator_already_provisioned.rc != 0
  become_user:               "{{ __sudo_user }}"

- name:                      Wait for ingress controller to become ready as per https://kubernetes.github.io/ingress-nginx/deploy/
  shell:                     kubectl wait --namespace {{ __default_namespace }} --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s
  become_user:               "{{ __sudo_user }}"
