---
- name:                       Create Docs user accounts and add them to the {{ sudo_group }} group
  user:
    name:                     "{{ docs_username }}"
    password:                 "{{ docs_password | password_hash('sha512') }}"
    groups:                   "{{ sudo_group }}"
    generate_ssh_key:         yes
    ssh_key_bits:             2048
    ssh_key_file:             .ssh/id_rsa
    ssh_key_passphrase:       "{{ docs_password }}"
    shell:                    /bin/bash
    append:                   yes
    state:                    present
  register:                   create_docs_user

- name:                       Convert ssh key for RHEL8
  command:                    ssh-keygen -p -m PEM -f /home/{{ docs_username }}/.ssh/id_rsa -P "{{ docs_password }}" -N "{{ docs_password }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name:                       Get default group name for {{ docs_username }}
  command:                    id -gn "{{ docs_username }}"
  register:                   user_group
  when:                       create_docs_user.changed

- name:                       Default group of {{ docs_username }}
  debug:
    msg:                      "{{  user_group.stdout }}"
  when:                       create_docs_user.changed

- name:                       Create authorized_keys for user
  copy:
    src:                      "/home/{{ docs_username }}/.ssh/id_rsa.pub"
    dest:                     "/home/{{ docs_username }}/.ssh/authorized_keys"
    owner:                    "{{ docs_username }}"
    group:                    "{{ user_group.stdout }}"
    mode:                     '0600'
    remote_src:               true
  when:                       create_docs_user.changed
