- name:                      Create Docs data local mount points
  file:
    path:                    "{{ item }}"
    state:                   directory
    mode:                    '0755'
  with_items:
   - "{{ __docs_data_local_path }}"

- name:                      Create Viewer data local mount points
  file:
    path:                    "{{ item }}"
    state:                   directory
    mode:                    '0755'
  with_items:
   - "{{ __viewer_data_local_path }}"
  when:                      inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"]

- name:                      Mount "{{ __docs_editor_files_dest }}" to "{{ __docs_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    dump:                    0
    passno:                  0
    state:                   mounted
    src:                     "{{ __docs_editor_files_dest }}"
    path:                    "{{ __docs_data_local_path }}"

- name:                      Mount "{{ __docs_viewer_files_dest }}" to "{{ __viewer_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    dump:                    0
    passno:                  0
    state:                   mounted
    src:                     "{{ __docs_viewer_files_dest }}"
    path:                    "{{ __viewer_data_local_path }}"
  when:                      inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"]
