---
__setup_environment:           "{{ setup_environment | default(true) }}"

__viewer_shared_storage_type:  "{{ viewer_shared_storage_type | default('nfs') }}"
__viewer_data_local_path:      "{{ viewer_data_local_path | default('/mnt/viewer_data') }}"
__viewer_data_remote_path:     "{{ viewer_data_remote_path | default('/nfs/viewer_data') }}"
__docs_viewer_files_dest:      "{{ nfsMasterAddress }}:{{ __viewer_data_remote_path }}"

__docs_shared_storage_type:    "{{ docs_shared_storage_type | default('nfs') }}"
__docs_data_local_path:        "{{ docs_data_local_path | default('/mnt/docs_data') }}"
__docs_data_remote_path:       "{{ docs_data_remote_path | default('/nfs/docs_data') }}"
__docs_editor_files_dest:      "{{ nfsMasterAddress }}:{{ __docs_data_remote_path }}"

__cnx_shared_storage_type:     "{{ cnx_shared_storage_type | default('nfs') }}"
__cnx_data_local_path:         "{{ cnx_data_local_path | default('/mnt/cnx_data') }}"
__cnx_data_remote_path:        "{{ cnx_data_remote_path | default('/nfs/data/shared') }}"
__cnx_data_nfs_dest:           "{{ nfsMasterAddress }}:{{ __cnx_data_remote_path }}"
