- name:                  Cleanup
  import_playbook:       ../hcl/cleanup.yml

- name:                  Setup NFS
  import_playbook:       ../third_party/setup-nfs.yml

- name:                  Setup Docker with Docker Registry
  import_playbook:       ../third_party/setup-docker-registry.yml

- name:                  Setup Kubernetes
  import_playbook:       ../third_party/kubernetes/setup-kubernetes-single-node.yml

- name:                  Setup Component Pack
  import_playbook:       ../hcl/setup-component-pack.yml
