- name:                      Unmount "{{ __customizer_js_files_mount }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   unmounted
    path:                    "{{ __customizer_js_files_mount }}"
  ignore_errors:             true
  register: result
  retries: 3
  delay: 15
  until: result is not failed

- name:                      Remove fstab entry for "{{ __customizer_js_files_mount }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   absent
    path:                    "{{ __customizer_js_files_mount }}"
  ignore_errors:             true

- name:                      Unmount "{{ __nfs_master_files_mount }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   unmounted
    path:                    "{{ __nfs_master_files_mount }}"
  ignore_errors:             true
  register: result
  retries: 3
  delay: 15
  until: result is not failed

- name:                      Remove fstab entry for "{{ __nfs_master_files_mount }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   absent
    path:                    "{{ __nfs_master_files_mount }}"
  ignore_errors:             true
