- name:                  Find the filename of {{ __app_name }} zip
  find:
    paths:               "{{ __extraction_folder }}/IBMConnectionsDocs-repo/native"
    patterns:            "{{ __zip_prefix }}_*.zip"
  register:              app_zip_name

- name:                  Create {{ __app_name }} installation folder
  file:
    path:                "{{ __extraction_folder }}/{{ __app_name }}"
    state:               directory

- name:                  Unzip {{ __app_name }} zip
  unarchive:
    src:                 "{{ app_zip_name.files[0].path }}"
    dest:                "{{ __extraction_folder }}/{{ __app_name }}"
    remote_src:          yes
    validate_certs:      false
  register:              unpacked_zip
  until:                 unpacked_zip is succeeded

- name:                  Add +x to "{{ __app_name }}" install script
  file:
    dest:                "{{ __extraction_folder }}/{{ __app_name }}/installer/install.sh"
    mode:                "740"

- name:                  Add +x to Editor Proxy web server update script
  file:
    dest:                "{{ __extraction_folder }}/{{ __app_name }}/installer/update_webserver.sh"
    mode:                "740"
  when:
    - __app_name  == __proxy_install_folder
