- name:                      Get chart and version
  shell:                     "helm search repo {{ __helm_repository_local_name }} {{ __helm_repo_flag }} | grep infrastructure | awk {'print $2'}"
  register:                  infrastructure_chart_version
  become_user:               "{{ __sudo_user }}"

- name:                      Found infrastructure chart version
  debug:
    msg:                     "{{ infrastructure_chart_version.stdout }}"

- name:                      "Render {{ __infrastructure_env }}"
  template:
    src:                     "helmvars/infrastructure.yml.j2"
    dest:                    "{{ __infrastructure_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Upgrade infrastructure
  command:                   "helm upgrade infrastructure {{ __helm_repository_local_name }}/infrastructure -i --version {{ infrastructure_chart_version.stdout }} -f {{ __infrastructure_env }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Wait for infrastructure to come up
  shell:                     kubectl wait --namespace {{ __default_namespace }} --for=condition=ready pod --selector=app=mongo --timeout=300s
  become_user:               "{{ __sudo_user }}"

- name:                      Check if appregistry-client is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i appregistry-client | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if appregistry-service is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i appregistry-service | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if haproxy is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i haproxy | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if mongo is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i mongo | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if redis-sentinel is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i redis-sentinel | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"

- name:                      Check if redis-server is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i redis-server | grep -i Running
  changed_when:              true
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
