- name:                    Get chart and version
  shell:                   "helm search repo {{ __helm_repository_local_name }} {{ __helm_repo_flag }} | grep connections-persistent-st | awk {'print $2'}"
  register:                connections_vol_chart_version
  become_user:             "{{ __sudo_user }}"

- name:                    "Render {{ __connections_volumes }}"
  template:
    src:                   "helmvars/connections-volumes.yml.j2"
    dest:                  "{{ __connections_volumes }}"
  become_user:             "{{ __sudo_user }}"

- name:                    Found connections-vol chart version
  debug:
    msg:                   "{{ connections_vol_chart_version.stdout }}"

- name:                    Upgrade connections-vol
  command:                 "helm upgrade connections-volumes {{ __helm_repository_local_name }}/connections-persistent-storage-nfs -i --version {{ connections_vol_chart_version.stdout }} -f {{ __connections_volumes }} --namespace {{ __default_namespace }} --wait"
  become_user:             "{{ __sudo_user }}"

- name:                    Check if connections-volumes pv are bound
  shell:                   kubectl get pv -n {{ __default_namespace }} | grep -i connections | grep -i Bound
  when:                    not __skip_pod_checks
  become_user:             "{{ __sudo_user }}"
