- name:                  Setup Nginx
  import_playbook:       third_party/setup-nginx.yml

- name:                  Setup Haproxy
  import_playbook:       third_party/setup-haproxy.yml

- name:                  Setup NFS
  import_playbook:       third_party/setup-nfs.yml

- name:                  Setup Docker with Docker Registry
  import_playbook:       third_party/setup-docker-registry.yml

- name:                  Setup Kubernetes
  import_playbook:       third_party/kubernetes/setup-kubernetes.yml

- name:                  Setup DB2
  import_playbook:       third_party/setup-db2.yml

- name:                  Setup Connections Wizards
  import_playbook:       hcl/setup-connections-wizards.yml

- name:                  Setup LDAP
  import_playbook:       third_party/setup-ldap.yml

- name:                  Setup IBM SDI
  import_playbook:       third_party/setup-tdi.yml

- name:                  Setup WAS ND
  import_playbook:       third_party/setup-webspherend.yml

- name:                  Setup Connections
  import_playbook:       hcl/setup-connections.yml

- name:                  Update HCL Connections
  import_playbook:       hcl/setup-connections-ifix.yml

- name:                  Setup Component Pack
  import_playbook:       hcl/setup-component-pack.yml
