---
- name: Check if fixes in files are already deployed
  shell: |
    db2 connect to files > /dev/null
    db2 -x select POSTSCHEMAVER from FILES.PRODUCT
    db2 connect reset > /dev/null
  become: true
  become_user: "{{ __db2_user }}"
  register: files_version

- name: Check if fixes wikis are already deployed
  shell: |
    db2 connect to wikis > /dev/null
    db2 -x select POSTSCHEMAVER from WIKIS.PRODUCT
    db2 connect reset > /dev/null
  become: true
  become_user: "{{ __db2_user }}"
  register: wikis_version

- name: Download and unzip database update for 6.5CR1
  unarchive:
    src: "{{ __cnx_db_updates_url }}/{{ __cnx_db_update_file }}"
    dest: "{{ __db_extraction_folder }}"
    remote_src: yes
  when: (files_version.stdout < 147.3) or (wikis_version.stdout < 147.3)
  retries: 3

- name: Update Files database
  command: "db2 -td@ -vf {{ __db_extraction_folder }}/65cr1-database-updates/From-65/db2/65-65CR1-files-db2.sql"
  become: true
  become_user: "{{ __db2_user }}"
  when: files_version.stdout < 147.3

- name: Update Wikis database
  command: "db2 -td@ -vf  {{ __db_extraction_folder }}/65cr1-database-updates/From-65/db2/65-65CR1-wikis-db2.sql"
  become: true
  become_user: "{{ __db2_user }}"
  when: wikis_version.stdout < 147.3
