---
- name:                    Setup WAS Application Session Management
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-app-session-mgmt

- name:                    Update WAS SSO in Global Security
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-config-sso-update

- name:                    Update WAS SSL configurations to TLSv1.2
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-update-ssl-config

- name:                    Change SSL protocol to TLSv1.2 in WAS ssl.client.props
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-set-ssl-client-tls

- name:                    Set JVM arguments for application servers to override default to TLS v1.2
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-set-jvm-args

- name:                    Set Session management to secure session cookies
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-set-session-mgmt-cookies
  vars:
    __restrict_cookies:   "true"

- name:                    Set WAS server JVM heap size if provided
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/connections/set_was_jvm_heap

- name:                    Setup Tiny MCE Editor
  hosts:                   dmgr
  become:                  true
  roles:
    - role: roles/third_party/tiny-editors-install
      vars:
        uninstall_tinyeditors: false
      when: install_tinyeditors | default(false) | lower | bool

- name:                    Restart DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - { role: roles/third_party/ibm/wasnd/was-dmgr-restart,
        when: pool_server is not defined }

- name:                    Restart WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - { role: roles/third_party/ibm/wasnd/was-nodeagent-stop, when: pool_server is not defined }
    - { role: roles/third_party/ibm/wasnd/was-nodeagent-start, when: pool_server is not defined }

- name:                    Restart CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-stop-cluster
    - roles/third_party/ibm/wasnd/was-dmgr-start-cluster

- name:                    Configure an extended user to enable the creation of an External Community
  import_playbook:         setup-extended-user.yml
