# Install Connections 6.5
---
- name:                    Gather facts
  hosts:                   nfs_servers
  tasks:                   []

- name:                    Setup NFS
  hosts:                   dmgr, was_servers
  become:                  true
  roles:
    - roles/third_party/nfs-install

- name:                    Setup Connections
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/connections

- name:                    Connections Post Install Config
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/connections/post_install_config

- name:                    Start CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-start-cluster

- name:                    Setup HTTP Servers on DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-config-webserver
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Restart DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-restart

- name:                    Restart WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-nodeagent-stop
    - roles/third_party/ibm/wasnd/was-nodeagent-start


- name:                    Configure HTTP Servers
  hosts:                   ihs_servers
  serial:                  1
  become:                  true
  roles:
    - roles/third_party/ibm/ihs/ibm-http-config-plgwct
    - roles/third_party/ibm/ihs/ibm-http-adminctl-restart
    - roles/third_party/ibm/ihs/ibm-http-httpdconf
    - roles/third_party/ibm/ihs/ibm-http-server-restart

- name:                    Restart CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-stop-cluster
    - roles/third_party/ibm/wasnd/was-dmgr-start-cluster

- name:                    Restart DMGR
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/third_party/ibm/wasnd/was-dmgr-restart
