- name:          Install pre-requisites Yum
  yum:
    name:        ['nfs-utils', 'gtk2', 'libXtst', 'xorg-x11-fonts-Type1', 'psmisc', 'glibc.i686', 'gtk2.i686', 'libXtst.i686', 'libXft.i686', 'unzip', 'vim', 'python3-pip', 'python-passlib.noarch']
    state:       present
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Amazon")

- name:          Set file descriptors limits
  pam_limits:
    domain:      '*'
    limit_type:  '-'
    limit_item:  nofile
    value:       '64000'

