---
  - name:                 "Verify if Profile already exists"
    stat:
      path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
    register:             profile_already_exists

  - name:                 Verify if pid file
    shell:                ps -p `cat "{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/dmgr/dmgr.pid"`
    register:             dmgr_is_running
    ignore_errors:        true

  - name:                 "Render {{ __ltpa_rsp_file }}"
    template:
      src:                "{{ __ltpa_tpl_file }}"
      dest:               "{{ __ltpa_rsp_file }}"

  - name:                 "Get/Set LTPA timeout in WAS {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f get_set_was_ltpa_timeout.py"
    command:
      chdir={{ __dmgr_bin_dir }}
      {{ __dmgr_bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f get_set_was_ltpa_timeout.py
    register:             cout
    changed_when:         cout.rc == 0
