---
- name:                   "Loop over the tasks until checksum matches"
  block:
    - name:               Set the retry count
      set_fact:
        retry_counter:      "{{ 0 if retry_counter is undefined else retry_counter|int + 1 }}"
        
    - name:               Show me the current retry count
      debug:
        msg:              "{{ retry_counter }}"        

    - name:               "Clean up { __cnx_package }}"
      file:
        path:             "{{ __tmp_dir }}/cnx/{{ __cnx_package }}"
        state: absent

    - name:               "Clean up { __cnx_package }}.sha256"
      file:
        path:             "{{ __tmp_dir }}/cnx/{{ __cnx_package }}.sha256"
        state: absent

    - name:               "Check if checksum file exists at {{ cnx_repository_url }}/{{ __cnx_package }}.sha256"
      uri:
        url:              "{{ cnx_repository_url }}/{{ __cnx_package }}.sha256"
        method:              HEAD
      register: checksum_file_exists
      ignore_errors: yes

    - name:               "Download checksum file if it exists to the {{ __tmp_dir }}/cnx/{{ __cnx_package }}.sha256"
      get_url:
        url:              "{{ cnx_repository_url }}/{{ __cnx_package }}.sha256"
        dest:             "{{ __tmp_dir }}/cnx"
      when: checksum_file_exists.status == 200

    - name:               "Read checksum from file from {{ __cnx_package }}.sha256 file"
      shell:              cat "{{ __tmp_dir }}/cnx"/"{{ __cnx_package }}".sha256
      register: checksum_value
      when: checksum_file_exists.status == 200

    - name:               "Download installation {{ __cnx_package }} to the {{ __tmp_dir }}/cnx"
      get_url:
        url:              "{{ cnx_repository_url }}/{{ __cnx_package }}"
        dest:             "{{ __tmp_dir }}/cnx"
        timeout:          300
        validate_certs:   false 

    - name:               "Calculate checksum of {{ __tmp_dir }}/cnx/{{ __cnx_package }}"
      shell:              sha256sum "{{ __tmp_dir }}/cnx"/"{{ __cnx_package }}" | cut -d' ' -f1
      register:           calculated_checksum
      when: checksum_file_exists.status == 200

    - name:               "Fail step if checksum values of {{ __cnx_package }} and {{ __cnx_package }}.sha256 are NOT matching"
      debug:
        msg:              "Downloaded file checksum is {{ calculated_checksum.stdout }} and .sha256 file content is {{ checksum_value.stdout }}"
      failed_when:        calculated_checksum.stdout != checksum_value.stdout
      when:               checksum_file_exists.status == 200

  rescue:
    - fail:
        msg: Ended after 5 retries
      when: retry_counter|int == 5

    - debug:
        msg:              "Failed to download file {{ __tmp_dir }}/cnx/{{ __cnx_package }}. Retrying..."

    - include_tasks:      download_connections_installer.yml
