# Setup Component Pack only (i.e. no post-install-config, restart server)
---
- name:                    Gather facts
  hosts:                   nfs_servers, was_servers
  tasks:                   []

- name:                    Setup Component Pack
  hosts:                   component_pack_master
  become:                  true
  roles:
    - roles/hcl/component-pack-harbor

# This is needed after enable_es_for_metrics
- name:                    Rerun Docs update_webserver script if installed
  import_playbook:         ../update-webserver-for-docs.yml
  when:
    - groups['proxy_servers'] is defined
