# Setup Component Pack
---
- name:                    Gather facts
  hosts:                   nfs_servers, was_servers
  tasks:                   []

- name:                    Setup Component Pack
  hosts:                   component_pack_master
  become:                  true
  roles:
    - roles/hcl/component-pack-harbor

- name:                    CNX Post Install Config for Component Pack
  hosts:                   dmgr
  become:                  true
  roles:
    - roles/hcl/component-pack-harbor/post-install-config

- name:                    Synchronize WAS nodes
  hosts:                   dmgr
  become:                  true
  roles:
    - { role: roles/third_party/ibm/wasnd/was-dmgr-full-sync-nodes,
        when: pool_server is not defined }

- name:                    Restart WAS Nodes
  hosts:                   was_servers
  serial:                  1
  become:                  true
  roles:
    - { role: roles/third_party/ibm/wasnd/was-nodeagent-stop,
        when: pool_server is not defined and was_defer_restart is not defined }
    - { role: roles/third_party/ibm/wasnd/was-nodeagent-start,
        when: pool_server is not defined and was_defer_restart is not defined }

- name:                    Restart CNX Clusters
  hosts:                   dmgr
  become:                  true
  roles:
    - { role: roles/third_party/ibm/wasnd/was-dmgr-stop-cluster,
        when: was_defer_restart is not defined }
    - { role: roles/third_party/ibm/wasnd/was-dmgr-start-cluster,
        when: was_defer_restart is not defined }
