- name:                  Clean up installation folder(s)
  file:
    path:                "{{ __extraction_folder }}"
    state:               absent

- name:                  Create installation folder
  file:
    path:                "{{ __extraction_folder }}"
    state:               directory

- name:                  Download and unzip installation {{ __download_location }}/{{ __package_name }} to the {{ __extraction_folder }}
  unarchive:
    src:                 "{{ __download_location }}/{{ __package_name }}"
    dest:                "{{ __extraction_folder }}"
    remote_src:          yes
  register: download_and_unpack_docs
  until: download_and_unpack_docs is succeeded
  retries: 3

- name:                  Unpack Docs Conversion installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          DocsConversion
    __zip_prefix:        "{{ __app_name }}"
  when:                  inventory_hostname in groups["conversion_servers"]

- name:                  Unpack Docs Editor installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          DocsEditor
    __zip_prefix:        DocsApp
  when:                  inventory_hostname in groups["docs_servers"]

- name:                  Unpack Docs Viewer installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          DocsViewer
    __zip_prefix:        Viewer
  when:                  inventory_hostname in groups["viewer_servers"]

- name:                  Unpack Editor Proxy installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          DocsProxy
    __zip_prefix:        DocsProxyFilter
  when:                  inventory_hostname in groups["proxy_servers"]

- name:                  Unpack Docs Editor Extension installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          DocsCnxExtension
    __zip_prefix:        DocsLCExtension
  when:                  inventory_hostname in groups["cnx_was_servers"]

- name:                  Unpack Docs Viewer Extensions installer
  include_role:
    name:                roles/hcl/docs/unpack_docs_installer
  vars:
    __app_name:          ViewerCnxExtension
    __zip_prefix:        ViewerLCCustomizeApp
  when:                  inventory_hostname in groups["cnx_was_servers"]
