- name:               Verify if Docs Viewer Extension is already installed
  stat:
    path:             "{{ __docs_viewer_ext_install_success_file }}"
  register:           viewer_ext_already_installed

- name:               Get CNX shared data mount target for {{ nfsMasterAddress }}:{{ cnx_data_nfs }}
  shell:              "findmnt --source {{ nfsMasterAddress }}:{{ cnx_data_nfs }} -o target -n | head -n 1"
  register:           cnx_data_mount_target
  when:
    - not viewer_ext_already_installed.stat.exists

- set_fact:
    local_cnx_data_path:    "{{ cnx_data_nfs }}"
  when:                     cnx_data_mount_target.stdout|length == 0

- set_fact:
    local_cnx_data_path:    "{{ cnx_data_mount_target.stdout }}"
  when:                     cnx_data_mount_target.stdout|length > 0

- debug:                    var=local_cnx_data_path
  when:
    - not viewer_ext_already_installed.stat.exists

- name:               Edit cfg.properties
  lineinfile:
    path:            "{{ __viewer_ext_cfg_prop_location }}/cfg.properties"
    regex:           "{{ item.prop_name }}"
    line:            "{{ item.prop_value }}"
    state:           present
  with_items:
    - { prop_name: "{{ __ext_install_root }}", prop_value: "{{ __viewer_ext_install_root_r }}" }
    - { prop_name: "{{ __was_install_root }}", prop_value: "{{ __was_install_root_r }}" }
    - { prop_name: "{{ __ic_extension_path }}", prop_value: "{{ __ic_extension_path }}{{ local_cnx_data_path }}/provision/webresources" }
    - { prop_name: "{{ __deamon_shared_path }}", prop_value: "{{ __deamon_shared_path }}{{ local_cnx_data_path }}" }
    - { prop_name: "{{ __auth_type }}", prop_value: "{{ __auth_type_r }}" }
    - { prop_name: "{{ __files_scope_name }}", prop_value: "{{ __files_scope_name_r }}" }
    - { prop_name: "{{ __news_scope_name }}", prop_value: "{{ __news_scope_name_r }}" }
    - { prop_name: "{{ __common_scope_name }}", prop_value: "{{ __common_scope_name_r }}" }
    - { prop_name: "{{ __viewer_server_url }}", prop_value: "{{ __viewer_server_url_r }}" }
    - { prop_name: "{{ __enable_upload_conversion }}", prop_value: "{{ __enable_upload_conversion_r }}" }
    - { prop_name: "{{ __viewer_admin_j2c_alias }}", prop_value: "{{ __viewer_admin_j2c_alias_r }}" }
  when:
    - not viewer_ext_already_installed.stat.exists

# Note: Documentation says it can be installed on one of the HCL Connections server
- name:              Run the Docs Viewer Extension installer
  shell:
    chdir:           "{{ __extraction_folder }}/ViewerCnxExtension/installer"
    cmd:             "./install.sh -wasadminID {{ was_username }} -wasadminPW {{ was_password }} -configFile cfg.properties -acceptLicense"
  become:            true
  when:
    - not viewer_ext_already_installed.stat.exists
  register:          sec_install_performed

- name:              Search for success message in install log
  become:            yes
  shell:             "grep -i '{{ __install_success_message }}' {{ __docs_viewer_ext_install_location }}/logs/extensionInstall.log"
  register:          viewer_ext_success_message_found
  failed_when:       viewer_ext_success_message_found.stdout|length == 0
  when:              sec_install_performed is not skipped

- name:              "Create {{ __docs_viewer_ext_install_success_file }} file"
  file:
    path:            "{{ __docs_viewer_ext_install_success_file }}"
    state:           touch
  when:              sec_install_performed is not skipped and viewer_ext_success_message_found.stdout|length > 0
