- name:                 Loop over IHS servers for plugin synchronization
  include_tasks:        sync_ihs_plugins.yml
  loop:                 "{{ groups['ihs_servers'] }}"
  loop_control:
    loop_var:           my_ihs_host

- name:                 "Copy the files to {{ __plg_install_location }}/config/"
  copy:
    src:                "/tmp/wct_generated_plugins_docs_{{ inventory_hostname_short }}/plugin-cfg.xml"
    dest:               "{{ __plg_install_location }}/config/{{ inventory_hostname_short }}/plugin-cfg.xml"
    remote_src:         yes
