---
- name:                    Map Docs Web Modules
  include_role:
    name:                  roles/third_party/ibm/wasnd/was-dmgr-map-modules
  vars:
    __app_name:            "{{ item.appname }}"
    __module:              "{{ item.module }}"
    __servers:             "{{ item.servers }}"
  with_items:
    - { appname: "IBMConversion", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __conversion_cluster_name }}" }
    - { appname: "IBMConversionSanity", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __conversion_cluster_name }}" }
    - { appname: "IBMDocs", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __editor_cluster_name }}" }
    - { appname: "IBMDocsSanity", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __editor_cluster_name }}" }
    - { appname: "IBMDocsWebResources", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __editor_cluster_name }}" }
    - { appname: "ViewerApp", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __viewer_cluster_name }}" }
    - { appname: "ViewerSanity", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __viewer_cluster_name }}" }
    - { appname: "Spellcheck4IBMDocs", module: ".*.war,.*", servers: "WebSphere:cell={{ __was_cellname }},cluster={{ __editor_cluster_name }}" }
    
