---
# Mandatory changes!

cnx_component_pack_ingress:                      "web.internal.example.com"
cnx_application_ingress:                         "connections.example.com"

# Usernames and password for eventual customization. Shown here are default usernames and password. Change it to customize it

was_username:                                    wasadmin
was_password:                                    password

ldap_userid:                                     "fakeuser"
ldap_nr_of_users:                                10
ldap_user_password:                              "password"
ldap_user_admin_password:                        "password"

ihs_username:                                    ihsadmin
ihs_password:                                    password

connections_admin:                               fakeuser1

db_password:                                     password
db_concord_password:                             password

docs_username:                                   docsuser
docs_password:                                   password
sudo_group:                                      wheel

tinyeditors_username:                            tinyeditorsuser
tinyeditors_password:                            password

# Non-mandatory changes

# Type of HCL Connections deployment: small (default), medium and large.
cnx_deploy_type:                                 medium
ldap_user_mail_domain:                           "connections.example.com"

connections_kit_folder:                          Connections8
db2_download_location:                           http://{{ groups['installer'][0] }}:8001/DB2
tdi_download_location:                           http://{{ groups['installer'][0] }}:8001/TDI
connections_wizards_download_location:           "http://{{ groups['installer'][0] }}:8001/{{ connections_kit_folder }}"
iim_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
was_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
was_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/was855FP23
ihs_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
ihs_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/was855FP23
cnx_docs_download_location:                      http://{{ groups['installer'][0] }}:8001/Docs
cnx_repository_url:                              "http://{{ groups['installer'][0] }}:8001/{{ connections_kit_folder }}"
tinyeditors_download_location:                   http://{{ groups['installer'][0] }}:8001/TinyEditors
cnx_fixes_repository_url:                        "http://{{ groups['installer'][0] }}:8001/{{ connections_kit_folder }}"

cnx_fixes_version:                               "8.0.0.0_CR3"
cnx_fixes_files:
  - { file_name: "HC8.0_CR3.zip" }

cnx_package:                                     "HCL_Connections_8.0_lin.tar"
connections_wizards_package_name:                "HCL_Connections_8.0_wizards_lin_aix.tar"
cnx_major_version:                               "8"

cnx_updates_enabled:                             True

dmgr_hostname:                                   "{{ hostvars[groups['dmgr'][0]]['inventory_hostname'] }}"

smtp_hostname:                                   localhost

connections_admin_password:                      "{{ ldap_user_admin_password }}"

db_username:                                     LCUSER
db_concord_username:                             docsuser
db_hostname:                                     "{{ hostvars[groups['db_servers'][0]]['inventory_hostname'] }}"
db_port:                                         50000
#db_jdbc_file:                                    /opt/IBM/db2/V11.5/java
db_type:                                         DB2
setup_db2_jdbc:                                  True

# set to true will drop and create databases
cnx_force_repopulation:                          false

cnx_enable_moderation:                           true
cnx_enable_invite:                               true
cnx_enable_full_icec:                            true

enable_prometheus_jmx_exporter:                  True

# uncomment to install CFix, update these for the latest fix and updateInstaller
# ifix_apar:                                       CFix.70.2110
# cnx_ifix_installer:                              "updateInstaller_2104.zip"
# ifix_file:                                       CFix.70.2110-IC7.0.0.0-Common-Fix.jar

component_pack_helm_repository:                  https://hclcr.io/chartrepo/cnx
docker_registry_url:                             hclcr.io/cnx
docker_registry_username:                        "{{ lookup('env','HARBOR_USERNAME') }}"
docker_registry_password:                        "{{ lookup('env','HARBOR_SECRET') }}"

huddoboards_registry_username:                   "{{ lookup('env','QUAY_USERNAME') }}"
huddoboards_registry_password:                   "{{ lookup('env','QUAY_SECRET') }}"

enable_pod_auto_scaling:                         true

load_balancer_dns:                               "{{ hostvars[groups['k8s_load_balancers'][0]]['inventory_hostname'] }}"
ic_internal:                                     "{{ hostvars[groups['ihs_servers'][0]]['inventory_hostname'] }}"
frontend_fqdn:                                   "{{ cnx_application_ingress }}"
frontend_domain:                                 "{{ cnx_application_ingress.split('.')[1:] | join('.') }}"
db_server:                                       "{{ db_hostname }}"
db_server_user:                                  "{{ db_username }}"
db_server_password:                              "{{ db_password }}"

# Docs variables
setup_connections_docs:                          true

docs_shared_storage_type:                        nfs
docs_data_remote_path:                           /nfs/docs_data
docs_data_local_path:                            /mnt/docs_data

viewer_shared_storage_type:                      nfs
viewer_data_remote_path:                         /nfs/viewer_data
viewer_data_local_path:                          /mnt/viewer_data

cnx_shared_storage_type:                         nfs
cnx_data_remote_path:                            /nfs/data/shared
cnx_data_local_path:                             /mnt/cnx_data

cnx_data_path_on_cnx_server:                     /opt/IBM/SharedArea

docs_url:                                        "{{ cnx_application_ingress }}"

# for cleanup playbooks
force_destroy_kubernetes:                        True
force_destroy_db2:                               True
force_destroy_ihs:                               True
force_destroy_websphere:                         True
