---
__profile_name: "{{ profile_name | default('Dmgr01') }}"
__was_cellname: "{{ was_cellname | default('ConnectionsCell') }}"
__app_profile_name: "{{ app_profile_name | default('AppSrv01') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__bin_dir: '{{ __was_install_location }}/profiles/{{ __profile_name }}/bin'

__cnx_uninstall: '{{ cnx_uninstall | default(false) }}'

__lcc_full_path: '{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{
  __was_cellname }}/LotusConnections-config/LotusConnections-config.xml'

# LCC configuration namepspaces
__lcc_namespaces: xmlns="http://www.ibm.com/LotusConnections-config" xsi="http://www.w3.org/2001/XMLSchema-instance"
  sloc="http://www.ibm.com/service-location" tns="http://www.ibm.com/LotusConnections-config"

# versionStamp
__lcc_versionstamp_xpath: /tns:config/tns:versionStamp
