- name:                      Unmount "{{ __docs_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   unmounted
    path:                    "{{ __docs_data_local_path }}"
  ignore_errors:             true
  register: result
  retries: 3
  delay: 15
  until: result is not failed

- name:                      Remove fstab entry for "{{ __docs_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   absent
    path:                    "{{ __docs_data_local_path }}"
  ignore_errors:             true

- name:                      Unmount "{{ __viewer_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   unmounted
    path:                    "{{ __viewer_data_local_path }}"
  ignore_errors:             true
  when:                      inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"]
  register: result
  retries: 3
  delay: 15
  until: result is not failed

- name:                      Remove fstab entry for "{{ __viewer_data_local_path }}"
  mount:
    fstype:                  nfs
    opts:                    defaults
    state:                   absent
    path:                    "{{ __viewer_data_local_path }}"
  ignore_errors:             true
  when:                      inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"]
