---
- name:                      Update LotusConnections-config.xml
  include_tasks:             update_lcc.yml

- name:                      Enable Moderation
  include_tasks:             setup_moderation.yml
  when:                      cnx_enable_moderation is defined and cnx_enable_moderation|bool

- name:                      Setup Invite config
  include_tasks:             setup_invite_config.yml
  when:                      __cnx_enable_invite|bool

- name:                      Setup Sharepoint Widget
  include_tasks:             setup_sharepoint_widget.yml

- name:                      Update files-config.xml to enable fileSync
  include_tasks:             update_files_config.yml

- name:                      Update mobile-config.xml to enable Push and MobileAdmin
  include_tasks:             update_mobile_config.yml

- name:                      Update applications J2EE reader role to All Authenticated Users
  include_role:
    name:               roles/third_party/ibm/wasnd/was-dmgr-j2ee-role-update
  vars:
    __app:                   "{{ item }}"
    __role:                  "reader"
    __everyone:              "no"
    __allauth:               "yes"
    __users:                 ""
    __groups:                ""
  with_items:
    - Communities
    - Profiles
  when:
    restrict_reader_access is defined and restrict_reader_access |bool


# not needed the relative url seems to be working
#- name:                 "Update widget-config.xml"
#  include_tasks:        update_widgets_config.yml
