---
  - name:              Update mobile-conifg.xml to enable Push
    xml:
      path:            "{{ __mobile_config_file }}"
      namespaces:      "{{ __mobilecfg_namespaces }}"
      xpath:           "{{ __mobilecfg_push_xpath }}"
      attribute:       "enabled"
      value:           "true"

  - name:              Update mobile-conifg.xml to enable MobileAdmin
    xml:
      path:            "{{ __mobile_config_file }}"
      namespaces:      "{{ __mobilecfg_namespaces }}"
      xpath:           "{{ __mobilecfg_mobileadmin_xpath }}"
      attribute:       "enabled"
      value:           "true"
