---
  __tmp_dir:                   "{{ tmp_dir | default('/opt/HCL/Binaries') }}"

# LDAP - OpenLDAP Ansible defaults

  __ldap_server_default:       "{{ hostvars[groups['ldap_servers'][0]]['inventory_hostname'] }}"
  __ldap_server:               "{{ ldap_server | default( __ldap_server_default ) }}"
  __ldap_bind_user:            "{{ ldap_bind_user | default('cn=Admin,ou=collab,dc=cnx,dc=pnp-hcl,dc=com') }}"
  __ldap_bind_pass:            "{{ ldap_bind_pass | default('password') }}"
  __ldap_realm:                "{{ ldap_realm | default('ou=collab,dc=cnx,dc=pnp-hcl,dc=com') }}"

# Globals

  __mt_zip:                    "{{ mt_zip | default('connections-mt-update-7.0.0.zip') }}"
  __product_id:                "\"id='com.ibm.connections'\""
  __mt_skip_error_checking:    "{{ mt_skip_error_checking  | default('false') }}"

  __cnx_install_location:      "{{ cnx_install_location  | default('/opt/HCL/Connections') }}"
  __was_install_location:      "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
  __ihs_install_location:      "{{ ihs_install_location  | default('/opt/IBM/HTTPServer') }}"

  __install_latest_db2:        "{{ install_latest_db2 | default(false) }}"
  __db2_default_install_path:  "{{ '/opt/IBM/db2/V11.5' if __install_latest_db2 else '/opt/IBM/db2/V11.1' }}"
  __db_installation_folder:    "{{ db2_installation_folder | default(__db2_default_install_path) }}"
  __profile_name:              "{{ profile_name | default('Dmgr01') }}"
  __app_profile_name:          "{{ app_profile_name | default('AppSrv01') }}"
  __was_cellname:              "{{ was_cellname | default('ConnectionsCell') }}"
  __dmgr_soap_port:            "{{ dmgr_soap_port | default(8879) }}"
  __ic_admin_username:         "{{ was_username | default('wasadmin') }}"
  __ic_admin_password:         "{{ was_password | default('password') }}"
  __db_user_name:              "{{ db_user | default('db2inst1') }}"
  __db_user_password:          "{{ db_password | default('password') }}"
  __ssh_passphrase:            "{{ ssh_passphrase | default(was_password) }}"
  __ldap_href_port:            "{{ ldap_href_port | default('389') }}"
  __ldap_provision_server:     "{{ ldap_provision_server | default( __ldap_server ) }}"
  __ldap_provision_port:       "{{ ldap_provision_port | default('389') }}"

# config.properties - AutoDeploy
  __dmgr_profile_r:            "{{ __was_install_location }}/profiles/{{ __profile_name }}"
  __dmgrname_profile_r:        "{{ __profile_name }}"
  __was_home_profile_r:        "{{ __was_install_location }}"
  __was_appsrv_profile_r:      "{{ __was_install_location }}/profiles/{{ __app_profile_name }}"
  __ihs_home_r:                "{{ __ihs_install_location }}"
  __dmgrsoap_port_r:           "{{ __dmgr_soap_port }}"
  __cell_name_r:               "{{ __was_cellname }}"
  __wasadmin_user_r:           "{{ __ic_admin_username }}"
  __wasadmin_password_r:       "{{ __ic_admin_password }}"
  __connections_path_r:        "{{ __cnx_install_location }}"
  __autodeploy_home_r:         "{{ autodeploy_install_location | default('/opt/HCL/autodeploy') }}"
  __autodeploy_auth_method_r:  "pubkey"
  __autodeploy_auth_r:         "/root/.ssh/{{ dmgr_hostname }}_key"
  __db_user_r:                 "{{ __db_user_name }}"
  __db_password_r:             "{{ __db_user_password }}"

# config.properties - Connections
  __mt_cnx_url_r:              "{{ ic_internal }}"
  __mt_ldap_url_r:             "ldap://{{ __ldap_server }}:{{ __ldap_href_port }}"
  __mt_ldap_auth_r:            "{{ mt_ldap_auth | default('simple') }}"
  __mt_ldap_sec_principal_r:   "{{ __ldap_bind_user }}"
  __mt_ldap_basedn_r:          "{{ __ldap_realm }}"
  __mt_ldap_sec_password_r:    "{{ __ldap_bind_pass }}"

# config.properties - OIDC
  __mt_oidc_enabled_r:         "{{ mt_oidc_enabled  | default('false') }}"
  __mt_oidc_realmname_r:       "{{ mt_oidc_realmname  | default('connmt') }}"
  __mt_oidc_identifier_r:      "{{ mt_oidc_identifier  | default('keycloak') }}"
  __mt_oidc_clientid_r:        "{{ mt_oidc_clientid  | default('mtdemo') }}"
  __mt_oidc_clientsecret_r:    "{{ mt_oidc_clientsecret  | default('') }}"
  __mt_oidc_rte_clientid_r:    "{{ mt_oidc_rte_clientid  | default('conn-rte') }}"
  __mt_oidc_rte_clientsecret_r:  "{{ mt_oidc_rte_clientsecret  | default('') }}"
  __mt_oidc_ee_clientid_r:     "{{ mt_oidc_ee_clientid  | default('conn-ee-kc') }}"
  __mt_oidc_ee_clientsecret_r: "{{ mt_oidc_ee_clientsecret | default('') }}"
  __mt_oidc_scope_r:           "{{ mt_oidc_scope | default('openid') }}"
  __mt_oidc_host_r:            "{{ mt_oidc_host | default('') }}"
  __mt_oidc_port_r:            "{{ mt_oidc_port | default('443') }}"
  __mt_oidc_discovery_url_r:   "{{ mt_oidc_discovery_url | default('') }}"
  __mt_oidc_auth_url_r:        "{{ mt_oidc_auth_url | default('') }}"
  __mt_oidc_token_url_r:       "{{ mt_oidc_token_url | default('') }}"
  __mt_oidc_logout_url_r:      "{{ mt_oidc_logout_url | default('') }}"
  __mt_oidc_introspect_url_r:  "{{ mt_oidc_introspect_url | default('') }}"
  __mt_oidc_jwk_url_r:         "{{ mt_oidc_jwk_url | default('') }}"
  __mt_oidc_issueid_url_r:     "{{ mt_oidc_issueid_url | default('') }}"
  __mt_oidc_signverifyalias_r: "{{ mt_oidc_signverifyalias | default('') }}"

# config.properties - MT provisioning
  __provision_mt_url_r:                        "{{ provision_mt_url | default( cnx_application_ingress ) }}"
  __provision_mt_ldap_url_r:                   "ldap://{{ __ldap_provision_server }}:{{ __ldap_provision_port }}"
  __provision_mt_ldapusername_r:               "{{ provision_mt_ldapusername | default( __ldap_bind_user ) }}"
  __provision_mt_ldappassword_r:               "{{ provision_mt_ldappassword | default( __ldap_bind_pass ) }}"
  __provision_mt_saasorgldapdn_r:              "cn=Organizations,{{ __ldap_realm }}"
  __provision_mt_defaultsubscriberlocal_r:     "{{ provision_mt_defaultsubscriberlocal | default('en_US') }}"
  __provision_mt_bssadminusername_r:           "{{ provision_mt_bssadminusername | default( __ic_admin_username ) }}"
  __provision_mt_bssadminpassword_r:           "{{ provision_mt_bssadminpassword | default( __ic_admin_password ) }}"
  __provision_mt_saasorgid_r:                  "{{ mt_saasorganization_id | default('ibm-socialOrganizationId') }}"
  __provision_mt_saassubscription_rdn_r:       "{{ mt_saassubscriptions_rdn | default('Users') }}"
  __provision_mt_saassubscription_id_r:        "{{ mt_saassubscription_id | default('ibm-socialPersonId') }}"
  __provision_mt_defaultquotasize_r:           "{{ provision_mt_defaultquotasize | default('524288000') }}"
  __provision_mt_defaulttransferquota_r:       "{{ provision_mt_defaulttransferquota | default('102410000') }}"
  __provision_mt_defaultallowdataoverage_r:    "{{ provision_mt_defaultallowdataoverage | default('true') }}"
  __provision_mt_ldap_org_filter_r:            "{{ provision_mt_ldap_org_filter | default('o=*') }}"
  __provision_mt_ldap_subscription_filter_r:   "{{ provision_mt_ldap_subscription_filter | default('uid=*') }}"

  __mt_update_success_file:            "{{ __cnx_install_location }}/mt.update.installed.success"
  __autodeploy_install_success_file:   "{{ __autodeploy_home_r }}/autodeploy.installed.success"
  __mt_update_ihs_success_file:        "{{ __ihs_install_location }}/mt.update.ihs.installed.success"
  __mt_update_db_success_file:        "{{ __db_installation_folder }}/mt.update.db.installed.success"
  __mt_update_was_success_file:        "{{ __cnx_install_location }}/mt.update.was.installed.success"
