- name:               Verify if Docs Editor Proxy  is already installed
  stat:
    path:             "{{ __editor_proxy_install_success_file }}"
  register:           editor_proxy_already_installed

- name:               Edit cfg.properties
  lineinfile:
    path:            "{{ __editor_proxy_cfg_prop_location }}/cfg.properties"
    regex:           "{{ item.prop_name }}"
    line:            "{{ item.prop_value }}"
    state:           present
  with_items:
    - { prop_name: "{{ __editor_install_root }}", prop_value: "{{ __editor_install_root_r }}" }
    - { prop_name: "{{ __was_proxy_profile_root }}", prop_value: "{{ __was_proxy_profile_root_r }}" }
    - { prop_name: "{{ __proxy_scope_name }}", prop_value: "{{ __proxy_scope_name_r }}" }
    - { prop_name: "{{ __scope }}", prop_value: "{{ __scope_r  }}" }
    - { prop_name: "{{ __docs_scope_name }}", prop_value: "{{ __docs_scope_name_r  }}" }
  when:
    - not editor_proxy_already_installed.stat.exists

# Note: Documentation says only need to install on one of the HCL Docs Proxy server nodes.
- name:              Run the Docs Editor Proxy installer
  shell:
    chdir:           "{{ __extraction_folder }}/{{ __proxy_install_folder }}/installer"
    cmd:             "./install.sh -wasadminID {{ was_username }} -wasadminPW {{ was_password }} -configFile cfg.properties -acceptLicense"
  become:            true
  when:
    - not editor_proxy_already_installed.stat.exists
  register:          sec_install_performed

- name:              Search for success message in install log
  become:            yes
  shell:             "grep -i '{{ __install_success_message }}' {{ __docs_editor_install_location }}/proxy/logs/proxy_install.log"
  register:          editor_proxy_success_message_found
  failed_when:       editor_proxy_success_message_found.stdout|length == 0
  when:              sec_install_performed is not skipped

- name:              "Create {{ __editor_proxy_install_success_file }} file"
  file:
    path:            "{{ __editor_proxy_install_success_file }}"
    state:           touch
  when:              sec_install_performed is not skipped and editor_proxy_success_message_found.stdout|length > 0
