- name:                 Synchronize /tmp/wct_generated_plugins_docs_{{ item }} from Dmgr to each IHS server
  synchronize:
    src:                /tmp/wct_generated_plugins_docs_{{ hostvars[item]['inventory_hostname_short'] }}/
    dest:               /tmp/wct_generated_plugins_docs_{{ hostvars[item]['inventory_hostname_short'] }}/
  delegate_to:          "{{ groups['dmgr'][0] }}"
  become:               false
  with_items:           "{{ groups['ihs_servers'] }}"

- name:                 Copy the files to /opt/IBM/WebSphere/Plugins/config/
  copy:
    src:                "/tmp/wct_generated_plugins_docs_{{ inventory_hostname_short }}/plugin-cfg.xml"
    dest:               "/opt/IBM/WebSphere/Plugins/config/{{ inventory_hostname_short }}/plugin-cfg.xml"
    remote_src:         yes
