__sudo_user:                                 "{{ kubectl_user | default( ansible_env['SUDO_USER'] ) | default('lcuser') }}"
__frontend_fqdn:                             "{{ groups['internal_lb'][0] if 'internal_lb' in groups else frontend_fqdn | default( inventory_hostname ) }}"
__default_namespace:                         "{{ default_namespace | default('connections') }}"
__trust_store_cert_dir_location:             "{{ '/tmp/' ~ __sudo_user ~ '/cnx-cec/certs' }}"
__trust_store_host:                          "{{ trust_store_host | default( __frontend_fqdn ) }}"
__trust_store_cert_file:                     "cnx-trust.pem"
__trust_store_https_port:                    "{{ trust_store_https_port | default(443) }}"
__trust_store_secret_key_name:               "connections.cer"
__trust_store_secret_name:                   "{{ trust_store_secret_name | default('connections-trust-secret') }}"
