---
- name:                     Create Conversion Server Cluster
  include_role:
    name: roles/third_party/ibm/wasnd/was-dmgr-create-cluster
  vars:
    __cluster_type:        "APPLICATION_SERVER"
    __cluster_name:        "{{ __conversion_cluster_name }}"
    __member_name:         "{{ __conversion_cluster_member_name }}"
    __server_list:         "{{ conversion_servers_list }}"

- name:                     Create Editor Server Cluster
  include_role:
    name: roles/third_party/ibm/wasnd/was-dmgr-create-cluster
  vars:
    __cluster_type:        "APPLICATION_SERVER"
    __cluster_name:        "{{ __editor_cluster_name }}"
    __member_name:         "{{ __editor_cluster_member_name }}"
    __server_list:         "{{ docs_servers_list }}"

- name:                     Create Viewer Server Cluster
  include_role:
    name: roles/third_party/ibm/wasnd/was-dmgr-create-cluster
  vars:
    __cluster_type:        "APPLICATION_SERVER"
    __cluster_name:        "{{ __viewer_cluster_name }}"
    __member_name:         "{{ __viewer_cluster_member_name }}"
    __server_list:         "{{ viewer_servers_list }}"

- name:                     Create Editor Proxy Cluster
  include_role:
    name: roles/third_party/ibm/wasnd/was-dmgr-create-cluster
  vars:
    __cluster_type:        "PROXY_SERVER"
    __cluster_name:        "{{ __docs_proxy_cluster_name }}"
    __member_name:         "{{ __docs_proxy_cluster_member_name }}"
    __generate_port:       True
    __template_name:       "proxy_server_foundation"
    __server_list:         "{{ proxy_servers_list }}"
