---
- name:              Disable Solr indexing and queries
  xml:
    path:            "{{ __searchcfg_full_path }}"
    namespaces:      "{{ __searchcfg_namespaces }}"
    xpath:           "{{ item.xpath }}"
    attribute:       "{{ item.attribute }}"
    value:           "{{ item.value }}"
  with_items:
    - { xpath: "{{ __searchcfg_qr_solr_xpath }}", attribute: "value", value: "false" }
    - { xpath: "{{ __searchcfg_queries_solr_xpath }}", attribute: "value", value: "false" }
  when:
    - __enable_es7_r_and_w |bool
    - __cnx_major_version == '7'

- name:              Enable ElasticSearch Indexing, Read, Write
  xml:
    path:            "{{ __searchcfg_full_path }}"
    namespaces:      "{{ __searchcfg_namespaces }}"
    xpath:           "{{ item.xpath }}"
    attribute:       "{{ item.attribute }}"
    value:           "{{ item.value }}"
    pretty_print:    yes
  with_items:
    - { xpath: "{{ __searchcfg_es_index_xpath }}", attribute: "value", value: "true" }
    - { xpath: "{{ __searchcfg_es_write_xpath }}", attribute: "value", value: "true" }
    - { xpath: "{{ __searchcfg_es_read_xpath }}", attribute: "value", value: "true" }
  when:
    - __enable_es7_r_and_w |bool
    - __cnx_major_version == '7'

- name:              Switch ES5 to ES7
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_es_version_xpath }}"
    value:           "{{ __lcc_es_version }}"
  when:
    - __enable_major_es7 |bool
    - __cnx_major_version == '7'

- name:              Enable Quick Results
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_qr_xpath }}"
    value:           "true"
  when:
    - __enable_qr |bool
    - __cnx_major_version == '7'

# repeat this step from enable_es_metrics.yml because it gets 404 sometimes
- name:                      Set config_blue_metrics.py command
  set_fact:
    __config_blue_metrics_cmd_python:  "{{ __config_blue_metrics_cmd }}"
  when:
    - not (ansible_os_family == "RedHat" and ansible_distribution_major_version == "8")

- name:                      Set config_blue_metrics.py command for RHEL8
  set_fact:
    __config_blue_metrics_cmd_python:  "/usr/bin/python2 {{ __config_blue_metrics_cmd }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name:                      Run {{ __config_blue_metrics_cmd }}
  shell:                     "{{ __config_blue_metrics_cmd_python }}"
  become:                    false
  register:                  configured_blue_metrics
  ignore_errors:             true
  delegate_to:               "{{ groups['component_pack_master'][0] }}"

- debug:                     var=configured_blue_metrics.stdout_lines
