# Cleanup
---
- name:                        Cleanup IHS
  hosts:                       ihs_servers
  become:                      true
  vars:
    force_destroy_kubernetes:  false
    force_destroy_db2:         false
    force_destroy_websphere:   false
    force_destroy_oracle:      false
  roles:
    - roles/hcl/cleanup

- name:                        Unmount NFS mounts on nfs_servers
  hosts:                       nfs_servers
  become:                      true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-dmgr-folders

- name:                        Cleanup NFS data on NFS master servers from IHS server
  hosts:                       nfs_servers
  become:                      true
  vars:
    force_destroy_kubernetes:  false
    force_destroy_db2:         false
    force_destroy_websphere:   false
    force_destroy_oracle:      false
    force_destroy_docs:        false
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data
