# Cleanup
---
- name:                        Cleanup Oracle
  hosts:                       oracle_servers
  become:                      true
  vars:
    force_destroy_kubernetes:  false
    force_destroy_db2:         false
    force_destroy_ihs:         false
    force_destroy_websphere:   false
  roles:
    - roles/hcl/cleanup
