# Cleanup
---
- name:                    Unmount Docs and Viewer NFS shares for Conversion, Docs and Viewer and Unmount CNX data NFS shares for Viewer
  hosts:                   docs_servers, conversion_servers, viewer_servers
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-nfs-docs-folders

- name:                    Cleanup NFS data on NFS master servers from Docs server
  hosts:                   nfs_servers
  become:                  true
  vars:
    force_destroy_websphere:   false
    force_destroy_db2:         false
    force_destroy_ihs:         false
    force_destroy_oracle:      false
    force_destroy_kubernetes:  false
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data
