# Cleanup
---
- name:                    Unmount NFS mounts on nfs_servers
  hosts:                   nfs_servers
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-dmgr-folders

- name:                    Unmount NFS mounts on component pack master
  hosts:                   component_pack_master
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-cp-folders

- name:                    Unmount Docs and Viewer NFS shares for Conversion, Docs and Viewer and Unmount CNX data NFS shares for Viewer
  hosts:                   docs_servers, conversion_servers, viewer_servers
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-nfs-docs-folders

- name:                    Cleanup NFS data on NFS master servers
  hosts:                   nfs_servers
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data

- name:                    Cleanup WebSphere and Connections folders
  hosts:                   dmgr, was_servers
  become:                  true
  roles:
    - roles/hcl/cleanup/cleanup-nfs-data/unmount-websphere-folders
