---
- name: Cleanup TDI
  hosts: db2_servers
  become: true
  vars:
    force_destroy_websphere: false
    force_destroy_kubernetes: false
    force_destroy_ihs: false
    force_destroy_oracle: false
    force_destroy_db2: false
  roles:
    - roles/hcl/cleanup
