---
  - name: Setup Sharepoint Widget
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { path: '{{ __widgets_config_file }}', regexp1: 'value="{clientId}"', replace: 'value="{{ sharepoint_client_id }}"'}
      - { path: '{{ __widgets_config_file }}', regexp1: 'value="{tenant}"', replace: 'value="{{ sharepoint_tenant_id }}"'}
    when: sharepoint_client_id is defined and sharepoint_tenant_id is defined
