- name:              Enable dynamicHosts
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ item.xpath }}"
    attribute:       "{{ item.attribute }}"
    value:           "{{ item.value }}"
  with_items:
    - { xpath: "{{ __lcc_dynamic_host_xpath }}", attribute: "enabled", value: "true" }
    - { xpath: "{{ __lcc_dynamic_host_href_xpath }}", attribute: "href", value: "{{ __lcc_dynamic_host_href }}" }
    - { xpath: "{{ __lcc_dynamic_host_href_xpath }}", attribute: "ssl_href", value: "{{ __lcc_dynamic_host_ssl_href }}" }
  when:              cnx_setup_mt is not defined or not cnx_setup_mt|bool
# Note: cnx_setup_mt is for internal use only, don't set to true

- name:              Enable forceConfidentalCommunication
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_force_comm_xpath }}"
    attribute:       "enabled"
    value:           "true"

- name:              Enable full ICEC
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_full_icec_xpath }}"
    value:           "false"
  when:              __cnx_enable_full_icec|bool

- name: Enable Languages in LotusConnections-config for {{ __profile_name }}
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_languageselector_xpath }}"
    attribute:       enabled
    value:           "true"
  when:              __cnx_enable_lang_selector|bool

- name: Update Languages in LotusConnections-config for {{ __profile_name }}
  xml:
    path:            "{{ __lcc_full_path }}"
    namespaces:      "{{ __lcc_namespaces }}"
    xpath:           "{{ __lcc_languageselector_xpath }}/tns:language[@lang=\"{{ item.lang }}\"]"
    value:           "{{ item.value }}"
    pretty_print:    yes
  with_items:
    - { lang: 'en', value: 'English' }
    - { lang: 'zh', value: '\u4e2d\u6587 (\u200f\u7b80\u4f53)' }
    - { lang: 'zh_tw', value: '\u4e2d\u6587 (\u200f\u7e41\u9ad4)' }
    - { lang: 'ko', value: '\ud55c\uad6d\uc5b4' }
    - { lang: 'fr', value: 'Fran\u00e7ais' }
    - { lang: 'de', value: 'Deutsch' }
    - { lang: 'it', value: 'Italiano' }
    - { lang: 'es', value: 'Espa\u00f1ol' }
    - { lang: 'pt_br', value: 'Portugu\u00eas (\u200fBrasil)' }
    - { lang: 'cs', value: '\u010ce\u0161tina' }
    - { lang: 'nl', value: 'Nederlands' }
    - { lang: 'fi', value: 'suomi' }
    - { lang: 'pl', value: 'polski' }
    - { lang: 'ru', value: '\u0420\u0443\u0441\u0441\u043a\u0438\u0439' }
    - { lang: 'iw', value: '\u05e2\u05d1\u05e8\u05d9\u05ea' }
    - { lang: 'ar', value: '\u200f\u0627\u0644\u0639\u0631\u0628\u064a\u0629\u200f' }
    - { lang: 'ca', value: 'Catal\u00e0' }
    - { lang: 'ja', value: '\u65e5\u672c\u8a9e' }
    - { lang: 'th', value: '\u0e44\u0e17\u0e22' }
  when:              __cnx_enable_lang_selector|bool
