---
__cnx_ifix_installer:              "{{ cnx_ifix_installer | default('updateInstaller.zip') }}"
__cnx_ifix_backup:                 "{{ cnx_ifix_backup | default('yes') }}"
__ifix_install_success_file:       "{{ __cnx_install_location }}/{{ ifix_apar }}.installed.success"

__cnx_install_location:            "{{ cnx_install_location  | default('/opt/HCL/Connections') }}"
__was_install_location:            "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__app_profile_name:                "{{ app_profile_name | default('AppSrv01') }}"
__profile_name:                    "{{ profile_name | default('Dmgr01') }}"

__product_id:                      "\"id='com.ibm.connections'\""
__tmp_dir:                         "{{ tmp_dir | default('/opt/IBM/Binaries') }}"
__was_cellname:                    "{{ was_cellname | default('ConnectionsCell') }}"
__cell_location:                   "{{ __was_install_location }}/profiles/{{ __profile_name }}/config/cells/{{ __was_cellname }}"
__cnx_major_version:               "{{ cnx_major_version | default('8') }}"
__cnx_ic360_cluster:               "{{ cnx_ic360_cluster | default('Apps') }}"
