---
- name:                  "Remove app server temp dir {{ __was_install_location }}/profiles/{{ __app_profile_name }}/temp"
  file:
    path:                "{{ __was_install_location }}/profiles/{{ __app_profile_name }}/temp/{{ inventory_hostname_short }}-node"
    state:               absent
  become:                true
  when:
   - inventory_hostname in groups["was_servers"]
   - cnx_updates_enabled |bool
   - not __cnx_uninstall

- set_fact:
    versionStampToSet:   "{{ '%Y%m%d.%H%M%S' | strftime(ansible_date_time.epoch) }}"

- debug:                 var=versionStampToSet

- name:                  Update versionStamp in LotusConnections-config.xml
  xml:
    path:                "{{ __lcc_full_path }}"
    namespaces:          "{{ __lcc_namespaces }}"
    xpath:               "{{ __lcc_versionstamp_xpath }}"
    attribute:           value
    value:               "{{ versionStampToSet }}"
  when:
    - inventory_hostname in groups["dmgr"]
    - cnx_updates_enabled |bool
    - not __cnx_uninstall
