---
# Mandatory changes!

cnx_component_pack_ingress:                      "web.internal.example.com"
cnx_application_ingress:                         "connections.example.com"

# Usernames and password for eventual customization. Shown here are default usernames and password. Change it to customize it

was_username:                                    wasadmin
was_password:                                    password

ldap_userid:                                     "fakeuser"
ldap_nr_of_users:                                1000
ldap_user_password:                              "password"
ldap_user_admin_password:                        "password"

ihs_username:                                    ihsadmin
ihs_password:                                    password

connections_admin:                               fakeuser1

db_password:                                     password
db_concord_password:                             password

docs_username:                                   docsuser
docs_password:                                   password
sudo_group:                                      wheel

tinyeditors_username:                            tinyeditorsuser
tinyeditors_password:                            password

# Non-mandatory changes

# Type of HCL Connections deployment: small (default), medium and large.
cnx_deploy_type:                                 medium
ldap_user_mail_domain:                           "connections.example.com"

db2_download_location:                           http://{{ groups['installer'][0] }}:8001/DB2
tdi_download_location:                           http://{{ groups['installer'][0] }}:8001/TDI
connections_wizards_download_location:           http://{{ groups['installer'][0] }}:8001/Connections7
iim_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
was_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
was_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/was855FP21
ihs_repository_url:                              http://{{ groups['installer'][0] }}:8001/was855
ihs_fixes_repository_url:                        http://{{ groups['installer'][0] }}:8001/was855FP21
cnx_docs_download_location:                      http://{{ groups['installer'][0] }}:8001/Docs
cnx_repository_url:                              http://{{ groups['installer'][0] }}:8001/Connections7
component_pack_download_location:                http://{{ groups['installer'][0] }}:8001/cp
tinyeditors_download_location:                   http://{{ groups['installer'][0] }}:8001/TinyEditors

iim_bin_file:                                    "agent.installer.linux.gtk.x86_64_1.9.1003.20200730_2125.zip"
iim_version:                                     "1.9.1003.20200730_2125"

was_files:
  - { "file_name": "CIK2HML.zip", "check_sum": "b1333962ba4b25c8632c7e4c82b472350337e99febac8f70ffbd551ca3905e83" }
  - { "file_name": "CIK2JML.zip", "check_sum": "b73ae070656bed6399a113c2db9fb0abaf5505b0d41c564bf2a58ce0b1e0dcd2" }
  - { "file_name": "CIK2IML.zip", "check_sum": "440b7ed82089d43b1d45c1e908bf0a1951fed98f2542b6d37c8b5e7274c6b1c9" }

ihs_files:
  - { "file_name": "CIK1VML.zip", "check_sum": "d63c59de4a5548e3d26e71fefb76193d41ac7585bc450c1e504287e0a6f746c9" }
  - { "file_name": "CIK1WML.zip", "check_sum": "ac00e7ab43cc528fe7f3ccd69aeb6564a2e738e7bc6e30e71fd2e0d4bd64f39e" }
  - { "file_name": "CIK1XML.zip", "check_sum": "94e3d9b70b139ad5fa0578da6857b295c5d2370c1b6ecb544c1e5757406fec90" }

cnx_updates_enabled:                             True

dmgr_hostname:                                   "{{ hostvars[groups['dmgr'][0]]['inventory_hostname'] }}"

smtp_hostname:                                   localhost

connections_admin_password:                      "{{ ldap_user_admin_password }}"

db_username:                                     LCUSER
db_concord_username:                             docsuser
db_hostname:                                     "{{ hostvars[groups['db_servers'][0]]['inventory_hostname'] }}"
db_port:                                         50000
db_type:                                         DB2
setup_db2_jdbc:                                  True

cnx_force_repopulation:                          True

cnx_enable_moderation:                           true
cnx_enable_invite:                               true

enable_prometheus_jmx_exporter:                  True

# uncomment these lines, set to the latest cFix to include it as part of the initial install 
# ifix_apar:                                       LO100079
# cnx_ifix_installer:                              "updateInstaller_2102.zip"
# ifix_file:                                       HCL_Connections_70_Update.jar

setup_docker_registry:                           true
component_pack_package_name:                     hybridcloud_latest.zip

enable_pod_auto_scaling:                         true

#setup_installation:                              false
#setup_images:                                    false
#setup_credentials:                               false
#setup_psp:                                       false
#setup_connections_volumes:                       false
#setup_bootstrap:                                 false
#setup_connections_env:                           false
#setup_infrastructure:                            false
#setup_customizer:                                false
#setup_elasticsearch7:                            false
#setup_community_ingress:                         false
#setup_teams:                                     false
#setup_tailored_exp:                              false
#setup_orientme:                                  false
#setup_dashboards:                                false
#setup_elasticstack:                              false
#setup_sanity:                                    false
#setup_kudosboards:                               false
#setup_outlook_addin:                             false
#enable_es_metrics:                               false
#enable_gk_flags:                                 false
#setup_ms_teams_extensions:                       false
#skip_configure_redis:                            True

kudos_boards_licence:                            "PASTE_YOUR_LICENCE_KEY_HERE"

docker_registry_url:                             "{{ hostvars[groups['docker_registry'][0]]['inventory_hostname'] }}:5000"
load_balancer_dns:                               "{{ hostvars[groups['k8s_load_balancers'][0]]['inventory_hostname'] }}"
ic_internal:                                     "{{ hostvars[groups['ihs_servers'][0]]['inventory_hostname'] }}"
frontend_fqdn:                                   "{{ cnx_application_ingress }}"
frontend_domain:                                 "{{ cnx_application_ingress.split('.')[1:] | join('.') }}"
db_server:                                       "{{ db_hostname }}"
db_server_user:                                  "{{ db_username }}"
db_server_password:                              "{{ db_password }}"

setup_connections_docs:                          true
setup_connections_wizards:                       true

docs_shared_storage_type:                        nfs
docs_data_remote_path:                           /nfs/docs_data
docs_data_local_path:                            /mnt/docs_data

viewer_shared_storage_type:                      nfs
viewer_data_remote_path:                         /nfs/viewer_data
viewer_data_local_path:                          /mnt/viewer_data

cnx_shared_storage_type:                         nfs
cnx_data_remote_path:                            /nfs/data/shared
cnx_data_local_path:                             /mnt/cnx_data

cnx_data_path_on_cnx_server:                     /opt/IBM/SharedArea

docs_url:                                        "{{ cnx_application_ingress }}"

force_destroy_db2:                               True
force_destroy_ihs:                               True
force_destroy_websphere:                         True
force_destroy_kubernetes:                        True
