---
- name:                      Update LotusConnections-config.xml
  include_tasks:             update_lcc_cp.yml

- name:                      Setup OrientMe and Action Center config
  include_tasks:             setup_orientme.yml

- name:                      Setup appregistry config
  include_tasks:             setup_appreg.yml

- name:                      Setup OpenSearch config
  include_tasks:             setup_elasticsearch_config.yml

- name:                      Setup Teams config
  include_tasks:             setup_teams_config.yml
  when:                      __setup_teams|bool

- name:                      Setup Connection Provider Huddo Boards
  include_tasks:             setup_conn_provider_kudosboards.yml
  when:                      __setup_huddoboards|bool

- name:                      Setup Huddo Boards Extension
  include_tasks:             setup_huddoboards_extension.yml
  when:                      __setup_huddoboards_ext|bool

- name:                      Synchronize configmap jwt-expires-in-minutes with WAS LTPA timeout
  include_tasks:             synch_ltpa_timeout.yml
