- name:                  Setup Nginx
  import_playbook:       third_party/setup-nginx.yml

- name:                  Setup NFS
  import_playbook:       third_party/setup-nfs.yml

- name:                  Setup Containerd
  import_playbook:       third_party/setup-containerd.yml

- name:                  Setup Kubernetes
  import_playbook:       third_party/kubernetes/setup-kubernetes.yml

- name:                  Setup Component Pack
  import_playbook:       hcl/harbor/setup-component-pack.yml
