- name:                  Setup Nginx
  import_playbook:       third_party/setup-nginx.yml

- name:                  Setup Haproxy
  import_playbook:       third_party/setup-haproxy.yml

- name:                  Setup NFS
  import_playbook:       third_party/setup-nfs.yml

- name:                  Setup Containerd
  import_playbook:       third_party/setup-containerd.yml

- name:                  Setup Kubernetes
  import_playbook:       third_party/kubernetes/setup-kubernetes.yml
