- name:                       Check if namespace {{ __default_namespace }} is already created
  shell:                      kubectl get namespace | grep {{ __default_namespace }}
  changed_when:               true
  register:                   connections_created
  become:                     false
  ignore_errors:              true

- name:                       Create namespace
  command:                    kubectl create namespace {{ __default_namespace }}
  when:                       connections_created.rc != 0
  become:                     false

- name:                       Delete credentials, to enable recreating it
  command:                    kubectl delete secret {{ __credentials_name }} -n {{ __default_namespace }}
  become:                     false
  ignore_errors:              true

- name:                       Setup credentials for private Docker Repository
  command:                    kubectl create secret docker-registry {{ __credentials_name }} -n {{ __default_namespace }} --docker-server={{ __docker_registry_url }} --docker-username={{ __docker_registry_username }} --docker-password {{ __docker_registry_password }}
  become:                     false
