- name:                      Find connections-env helm file
  find:
    paths:                   "{{ __helmbuilds_folder }}"
    patterns:                "connections-env-*.tgz"
    file_type:               file
  register:                  connectionsenv_tgz

- name:                      Found connections-env file
  debug:
    msg:                     "{{ connectionsenv_tgz.files[0].path }}"

- name:                      "Render {{ __connections_env_install_env }}"
  template:
    src:                     "helmvars/connections-env.yml.j2"
    dest:                    "{{ __connections_env_install_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Setup connections-env
  command:                   "helm upgrade connections-env {{ connectionsenv_tgz.files[0].path }} -i -f {{ __connections_env_install_env }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Give it some space...
  pause:
    seconds:                 10

- name:                      Check if connections-env configmap is created
  shell:                     kubectl get configmap -n {{ __default_namespace }} | grep -i connections-env
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
