- name:                      Find elasticsearch helm file
  find:
    paths:                   "{{ __helmbuilds_folder }}"
    patterns:                "elasticsearch-*.tgz"
    file_type:               file
  register:                  elasticsearch_tgz

- name:                      Found elasticsearch file
  debug:
    msg:                     "{{ elasticsearch_tgz.files[0].path }}"

- name:                      "Render {{ __elasticsearch_env }}"
  template:
    src:                     "helmvars/elasticsearch.yml.j2"
    dest:                    "{{ __elasticsearch_env }}"
  become:                    false

- name:                      Setup elasticsearch
  command:                   "helm upgrade elasticsearch {{ elasticsearch_tgz.files[0].path }} -i -f {{ __elasticsearch_env }} --recreate-pods"
  become:                    false

- name:                      Give it some space...
  pause:
    seconds:                 300

- name:                      Check if es-master is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i es-master | grep -i Running
  when:                      not __skip_pod_checks
  become:                    false

- name:                      Check if es-client is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i es-client | grep -i Running
  when:                      not __skip_pod_checks
  become:                    false

- name:                      Check if es-data is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i es-data | grep -i Running
  when:                      not __skip_pod_checks
  become:                    false
